"""The scope gate must fail CLOSED, and must not depend on its own CWD.

Gap-class #9 in prd-os's own catalog (`templates/gap-classes.md`):

    A gate fails CLOSED; a filter may fail OPEN. The same check has opposite
    correct failure modes: a launch/action gate must refuse when it cannot
    verify.

Measured 2026-08-05 against the shipped hook: the SAME payload naming the SAME
repo-relative disallowed path was BLOCKED (rc=2) when the hook process happened
to run inside the repo and ALLOWED (rc=0) when it ran anywhere else.

Mechanism -- a derivation split. `_outside_repo` takes the repo root from
`payload["cwd"]` but resolves the target with `Path(file_path).resolve()`,
which resolves against the HOOK PROCESS's cwd. When those differ, an in-repo
file resolves to a path under the wrong parent, `relative_to(root)` raises,
the target is judged "outside the repo", and the hook returns 0. The gate
silently disables itself, with no warning, in exactly the direction that
protects nothing.

The out-of-repo carve-out itself is deliberate and stays: a path outside the
repo cannot appear in the issue's diff, and blocking it broke real scratchpad
work. What is fixed is WHICH directory a relative path is resolved against.
"""
import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

DSSE = Path(__file__).resolve().parent
HOOK = DSSE.parent / "hooks/scope_hook.py"

# The runner refuses a spec without prd_split's provenance marker ("issue spec
# rejected: marker not generated by prd_split.py"), which is a good guard: a
# hand-written spec cannot enter the workflow. Same marker shape the existing
# fixtures use.
_MARKER = (
    "<!-- generated-by: prd_split.py prd=prd-fixture finding=finding-fixture "
    "at=2026-04-20T00:00:00Z -->"
)

SPEC = f"""---
id: probe-1
title: probe
status: in-progress
priority: p0
allowed_files:
  - README.md
disallowed_files: []
required_checks:
  - python3 -c "print('ok')"
required_reviews: []
---
{_MARKER}

Fixture.
"""


@pytest.fixture()
def repo(tmp_path: Path) -> Path:
    r = tmp_path / "repo"
    r.mkdir()
    for cmd in (["init", "-q"], ["config", "user.email", "t@t.co"],
                ["config", "user.name", "t"]):
        subprocess.run(["git", *cmd], cwd=r, capture_output=True)
    (r / "README.md").write_text("# t\n")
    subprocess.run(["git", "add", "-A"], cwd=r, capture_output=True)
    subprocess.run(["git", "commit", "-qm", "i"], cwd=r, capture_output=True)
    issues = r / ".prd-os/issues"
    issues.mkdir(parents=True)
    (issues / "probe-1.md").write_text(SPEC)
    runner = DSSE / "issue_runner.py"
    assert subprocess.run([sys.executable, str(runner), "load", "probe-1"],
                          cwd=r, capture_output=True).returncode == 0
    return r


def _hook(payload: dict, run_from: Path):
    env = dict(os.environ)
    env.pop("ISSUE_GATE_OFF", None)
    return subprocess.run([sys.executable, str(HOOK)], cwd=run_from,
                          input=json.dumps(payload), capture_output=True,
                          text=True, env=env)


def _edit(path: str, repo: Path) -> dict:
    return {"tool_name": "Edit", "tool_input": {"file_path": path},
            "cwd": str(repo)}


def test_blocks_disallowed_path_when_run_from_the_repo(repo: Path):
    """Control. This already passed before the fix; it is here so a regression
    that breaks the ordinary path is not mistaken for the bug below."""
    assert _hook(_edit("src/secret.py", repo), run_from=repo).returncode == 2


def test_blocks_the_same_path_when_run_from_anywhere_else(repo: Path, tmp_path: Path):
    """The bug: identical payload, different hook cwd, opposite verdict."""
    elsewhere = tmp_path / "elsewhere"
    elsewhere.mkdir()
    proc = _hook(_edit("src/secret.py", repo), run_from=elsewhere)
    assert proc.returncode == 2, (
        "scope gate FAILED OPEN because the hook process ran outside the repo; "
        "the same payload blocks when run from inside it"
    )


def test_verdict_is_identical_from_both_directories(repo: Path, tmp_path: Path):
    """States the invariant directly: the hook's own cwd must not be an input
    to the decision. Stronger than the two cases above, which could both be
    satisfied by a rule that happens to block everything."""
    elsewhere = tmp_path / "elsewhere2"
    elsewhere.mkdir()
    for path in ("src/secret.py", "README.md", "docs/x.md"):
        inside = _hook(_edit(path, repo), run_from=repo).returncode
        outside = _hook(_edit(path, repo), run_from=elsewhere).returncode
        assert inside == outside, (
            f"{path!r}: rc={inside} from the repo but rc={outside} from "
            f"elsewhere -- the hook's cwd is an input to the verdict"
        )


def test_allowed_file_still_passes_from_elsewhere(repo: Path, tmp_path: Path):
    """Negative-fire: the fix must not turn the gate into block-everything.
    Without this, a hook that always exits 2 would satisfy every test above."""
    elsewhere = tmp_path / "elsewhere3"
    elsewhere.mkdir()
    assert _hook(_edit("README.md", repo), run_from=elsewhere).returncode == 0


def test_out_of_repo_target_is_still_allowed(repo: Path, tmp_path: Path):
    """The deliberate carve-out stays. A path outside the repo cannot appear in
    the issue's diff, and blocking it forced real scratchpad work to choose
    between ISSUE_GATE_OFF=1 and routing around the hook entirely. Only the
    resolution base is being fixed, not the policy."""
    outside = tmp_path / "outside.py"
    proc = _hook(_edit(str(outside), repo), run_from=repo)
    assert proc.returncode == 0, (
        "the out-of-repo carve-out was removed; that is a policy change, not "
        "this fix"
    )


def test_absolute_in_repo_path_blocks_from_either_directory(repo: Path, tmp_path: Path):
    """An absolute path carries its own base, so it must be immune to cwd."""
    elsewhere = tmp_path / "elsewhere4"
    elsewhere.mkdir()
    target = str(repo / "src/secret.py")
    assert _hook(_edit(target, repo), run_from=repo).returncode == 2
    assert _hook(_edit(target, repo), run_from=elsewhere).returncode == 2


# ---------------------------------------------------------------------------
# Stop gate: the exhaustion loop-break must be COUNTED, not silent
# ---------------------------------------------------------------------------

STOP_GATE = DSSE.parent / "hooks/stop_gate.py"


def _stop(repo: Path, payload: dict):
    env = dict(os.environ)
    env.pop("ISSUE_GATE_OFF", None)
    env["CLAUDE_PROJECT_DIR"] = str(repo)
    return subprocess.run([sys.executable, str(STOP_GATE)], cwd=repo,
                          input=json.dumps(payload), capture_output=True,
                          text=True, env=env)


def _clear_receipts(repo: Path) -> None:
    state = repo / ".claude/state/active-issue.json"
    d = json.loads(state.read_text())
    d["receipts"] = {k: None for k in d.get("receipts", {})}
    state.write_text(json.dumps(d, indent=2))


def test_stop_gate_refuses_while_receipts_are_missing(repo: Path):
    """Control: the gate does its job on the first firings."""
    subprocess.run([sys.executable, str(DSSE / "issue_runner.py"), "approve"],
                   cwd=repo, capture_output=True)
    _clear_receipts(repo)
    assert _stop(repo, {}).returncode == 2


def test_stop_gate_exhaustion_is_recorded_not_silent(repo: Path):
    """The exhaustion is a legitimate loop-break -- a Stop hook that blocks
    forever hangs the session, and `stop_hook_active` (the documented primary
    break) is honored, so this backup is rare. What it must not be is SILENT.

    Measured 2026-08-05: after 3 firings the gate allows the session to end
    with all three receipts missing, and the only trace is a counter in
    `.claude/state/`, which is ephemeral per-session state, not a ledger. A
    session can end un-receipted and nothing durable records that it did.

    Same shape as ISSUE_GATE_OFF, so the same fix: one countable row.
    """
    subprocess.run([sys.executable, str(DSSE / "issue_runner.py"), "approve"],
                   cwd=repo, capture_output=True)
    _clear_receipts(repo)
    for _ in range(3):
        assert _stop(repo, {}).returncode == 2
    exhausted = _stop(repo, {})
    assert exhausted.returncode == 0, "precondition: the 4th firing exhausts"

    ledger = repo / ".prd-os/gate-bypasses.jsonl"
    assert ledger.is_file(), (
        "the gate let a session end with missing receipts and left no durable "
        "record"
    )
    rows = [json.loads(l) for l in ledger.read_text().splitlines() if l.strip()]
    row = rows[-1]
    assert row["env"] == "stop-gate-exhaustion"
    assert row.get("issue_id") == "probe-1"
    assert row.get("missing_receipts"), (
        "the row does not say WHAT was missing, so it cannot be audited later"
    )


def test_stop_gate_writes_no_bypass_row_while_it_is_still_refusing(repo: Path):
    """Negative-fire: only the exhaustion is a bypass. A refusal is the gate
    working, and counting it would drown the real signal."""
    subprocess.run([sys.executable, str(DSSE / "issue_runner.py"), "approve"],
                   cwd=repo, capture_output=True)
    _clear_receipts(repo)
    assert _stop(repo, {}).returncode == 2
    assert not (repo / ".prd-os/gate-bypasses.jsonl").exists()


def test_scope_gate_fails_closed_when_the_runner_errors(monkeypatch, tmp_path):
    """A gate whose failure mode is "permit" is not a gate.

    This returned ALLOW until Codex round 4 produced a repro: a runner timeout
    silently disabled scope enforcement for the rest of the session. The suite
    in this file claimed the gate fails closed while never testing its error
    path -- the claim and the code disagreed, and only the claim was tested.
    """
    import io as _io, json as _json, sys as _sys
    from pathlib import Path as _Path
    _sys.path.insert(0, str(_Path(__file__).resolve().parents[1] / "hooks"))
    import scope_hook as h

    payload = {"tool_name": "Edit",
               "tool_input": {"file_path": "src/disallowed.py"},
               "cwd": str(tmp_path)}
    monkeypatch.setattr(h, "_outside_repo", lambda path, cwd: False)

    def _boom(*a, **k):
        raise TimeoutError("runner timed out")

    monkeypatch.setattr(h.subprocess, "run", _boom)
    monkeypatch.setattr(_sys, "stdin", _io.StringIO(_json.dumps(payload)))
    assert h.main() == 2, "runner error allowed the edit through unchecked"


@pytest.mark.parametrize("rc", [1, 3, 127, -1])
def test_scope_gate_fails_closed_on_any_non_verdict_exit(monkeypatch, tmp_path, rc):
    """Only 0 allows; only 2 is a real scope refusal.

    Round 4 closed the raised-exception path and stopped there. Codex round 5
    showed the hole open one step over: a runner that CRASHES exits 1, which is
    not an exception in this process, and the hook read it as allow. Two
    spellings of one failure; closing either alone closes nothing.
    """
    import io as _io, json as _json, sys as _sys, subprocess as _sp
    from pathlib import Path as _Path
    _sys.path.insert(0, str(_Path(__file__).resolve().parents[1] / "hooks"))
    import scope_hook as h

    payload = {"tool_name": "Edit",
               "tool_input": {"file_path": "src/disallowed.py"},
               "cwd": str(tmp_path)}
    monkeypatch.setattr(h, "_outside_repo", lambda path, cwd: False)
    monkeypatch.setattr(
        h.subprocess, "run",
        lambda *a, **k: _sp.CompletedProcess(a[0] if a else [], rc, "", "boom"))
    monkeypatch.setattr(_sys, "stdin", _io.StringIO(_json.dumps(payload)))
    assert h.main() == 2, f"runner exit {rc} was treated as permission to edit"


def test_scope_gate_still_allows_on_a_clean_in_scope_verdict(monkeypatch, tmp_path):
    """The negative half: the fix must not block everything."""
    import io as _io, json as _json, sys as _sys, subprocess as _sp
    from pathlib import Path as _Path
    _sys.path.insert(0, str(_Path(__file__).resolve().parents[1] / "hooks"))
    import scope_hook as h

    payload = {"tool_name": "Edit",
               "tool_input": {"file_path": "src/allowed.py"},
               "cwd": str(tmp_path)}
    monkeypatch.setattr(h, "_outside_repo", lambda path, cwd: False)
    monkeypatch.setattr(
        h.subprocess, "run",
        lambda *a, **k: _sp.CompletedProcess(a[0] if a else [], 0, "", ""))
    monkeypatch.setattr(_sys, "stdin", _io.StringIO(_json.dumps(payload)))
    assert h.main() == 0, "an in-scope edit was blocked"
