#!/usr/bin/env python3
"""Deterministic PRD -> issue-spec decomposition for the prd-os plugin.

Reads an approved PRD, locates the fenced JSON block under the `## Issues`
heading, and writes one issue spec per entry using `templates/issue.md`.

Design constraints:
  - No LLM. The PRD author (or a reviewed Codex pass) writes the JSON manifest
    inside the PRD; this script only materializes it.
  - PRD status MUST be `approved`. Any other status is rejected with exit 2.
  - Refuses to clobber existing issue files. A rerun is idempotent only when
    every entry already exists with byte-identical content; otherwise the
    rerun stops and reports the collision.
  - Required keys per manifest entry: id, title, allowed_files (non-empty
    list), required_checks (non-empty list). Optional: priority (default
    `p1`), disallowed_files, required_reviews, acceptance.
  - `required_checks` is enforced here — not in the issue runner — because
    the runner's stop-gate only checks three receipt timestamps (verified,
    reviewed, findings_triaged). Those receipts are meaningless unless the
    spec documents what must be verified. Allowing an empty (or missing)
    `required_checks` list lets an issue be "verified" against nothing,
    which silently bypasses the verification gate. Catching it here stops
    empty-check specs before they land on disk.

Invocation:
  python3 prd_split.py [--repo-root <path>] [--prd-id <id>] [--dry-run]
  python3 prd_split.py --from-linear <ASK-n> [--linear-json <path>] [--dry-run]

If --prd-id is omitted, the currently-active PRD (from the PRD runner's
state file) is used. --dry-run prints the planned writes without touching
disk.

--from-linear is an additive second entry point (ASK-214). It branches BEFORE
PRD resolution, so every pre-existing invocation is byte-identical. A Linear
issue has no parent PRD, so no legitimate spec could exist for Linear work; the
issue runner's `load` refused it on provenance and `close` could therefore never
write a receipt. That made the PR receipt gate block 100% of its target
population forever. This mode makes a receipt PRODUCIBLE by teaching the real
emitter to emit from a Definition of Ready. The marker stays honest and
unchanged in format -- prd_split.py really is the emitter -- with the real
provenance in its fields: `prd=linear:<ASK-n> finding=linear-dor`.

Exit codes:
  0  success (or dry-run with no errors)
  2  any validation or state error

This script is intentionally independent of the issue runner. It never
mutates issue-runner state; a split PRD produces specs that the issue
runner will then `load` one at a time.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

sys.path.insert(0, str(Path(__file__).resolve().parent))
from config import Config, ConfigError, load as load_config  # noqa: E402


TEMPLATE_RELPATH = Path(__file__).resolve().parent.parent / "templates" / "issue.md"
ISSUE_ID_RE = re.compile(r"^[a-z0-9][a-z0-9-]*[a-z0-9]$")
REQUIRED_KEYS = ("id", "title", "finding_id", "allowed_files", "required_checks")
REQUIRED_NONEMPTY_LIST_KEYS = ("allowed_files", "required_checks")
OPTIONAL_LIST_KEYS = ("disallowed_files", "required_reviews")
DEFAULT_PRIORITY = "p1"
GATE_LIFECYCLES = {
    "regression",
    "historical-receipt",
    "retired",
    "external",
}

# Provenance marker: identifies a spec as generated by this tool. The
# issue runner rejects specs without a conforming marker. Format must
# match kipi-dsse/issue_runner.py MARKER_RE.
MARKER_RE = re.compile(
    r"<!--\s+generated-by:\s+prd_split\.py\s+"
    r"prd=(?P<prd>\S+)\s+finding=(?P<finding>\S+)\s+at=(?P<at>\S+)\s+-->"
)


def _format_marker(prd_id: str, finding_id: str, at_iso: str) -> str:
    return (
        f"<!-- generated-by: prd_split.py "
        f"prd={prd_id} finding={finding_id} at={at_iso} -->"
    )


def _extract_existing_marker_timestamp(target: Path) -> Optional[str]:
    """Return the `at=` timestamp from an existing spec's marker, if any.

    Used to keep reruns byte-identical: if the target already has a
    well-formed marker, reuse its timestamp rather than stamping `now`.
    """
    if not target.is_file():
        return None
    try:
        text = target.read_text()
    except OSError:
        return None
    # Locate the line after the frontmatter close.
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    body = text[end + len("\n---"):]
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        m = MARKER_RE.fullmatch(stripped)
        return m.group("at") if m else None
    return None


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# ---------------------------------------------------------------------------
# PRD parsing
# ---------------------------------------------------------------------------


def _parse_frontmatter(text: str) -> tuple[dict, int]:
    """Return (frontmatter_dict, body_start_offset)."""
    if not text.startswith("---"):
        raise ValueError("PRD missing YAML frontmatter")
    end = text.find("\n---", 3)
    if end == -1:
        raise ValueError("PRD frontmatter not closed with ---")
    block = text[3:end].strip("\n")
    result: dict = {}
    for raw in block.splitlines():
        line = raw.rstrip()
        if not line or line.lstrip().startswith("#"):
            continue
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        result[key.strip()] = value.strip()
    # end marker is "\n---"; body starts after the next newline following that.
    body_start = end + len("\n---")
    nl = text.find("\n", body_start)
    body_start = nl + 1 if nl != -1 else len(text)
    return result, body_start


def _extract_issues_block(body: str) -> str:
    """Return the fenced JSON block under the `## Issues` heading.

    Accepts either ```json ...``` or ``` ... ``` (first fenced block after
    the Issues heading). Raises ValueError when the heading or block is
    missing.
    """
    m = re.search(r"(?m)^##\s+Issues\s*$", body)
    if not m:
        raise ValueError("PRD is missing a `## Issues` section")
    rest = body[m.end():]
    fence = re.search(r"```(?:json)?\s*\n(.*?)\n```", rest, flags=re.DOTALL)
    if not fence:
        raise ValueError("no fenced code block found under `## Issues`")
    return fence.group(1)


# ---------------------------------------------------------------------------
# Manifest validation
# ---------------------------------------------------------------------------


def _validate_entry(entry: object, index: int, id_re: re.Pattern = ISSUE_ID_RE) -> dict:
    # id_re is a parameter only so the Linear entry point can pass its own
    # (uppercase `ASK-214`) id shape. The default keeps PRD-manifest behaviour
    # byte-identical.
    if not isinstance(entry, dict):
        raise ValueError(f"entry #{index}: must be a JSON object")
    for key in REQUIRED_KEYS:
        if key not in entry:
            raise ValueError(f"entry #{index}: missing required key {key!r}")
    issue_id = entry["id"]
    if not isinstance(issue_id, str) or not id_re.match(issue_id):
        raise ValueError(
            f"entry #{index}: id must match {id_re.pattern!r}; got {issue_id!r}"
        )
    title = entry["title"]
    if not isinstance(title, str) or not title.strip():
        raise ValueError(f"entry #{index}: title must be a non-empty string")
    finding_id = entry["finding_id"]
    if not isinstance(finding_id, str) or not finding_id.strip():
        raise ValueError(
            f"entry #{index}: finding_id must be a non-empty string"
        )
    for key in REQUIRED_NONEMPTY_LIST_KEYS:
        v = entry[key]
        if not isinstance(v, list) or not v:
            raise ValueError(
                f"entry #{index}: {key} must be a non-empty list "
                "(empty list would silently bypass the verification gate)"
            )
        if not all(isinstance(x, str) and x for x in v):
            raise ValueError(
                f"entry #{index}: {key} entries must be non-empty strings"
            )
    for key in OPTIONAL_LIST_KEYS:
        if key in entry:
            v = entry[key]
            if not isinstance(v, list) or not all(isinstance(x, str) and x for x in v):
                raise ValueError(
                    f"entry #{index}: {key} must be a list of non-empty strings"
                )
    priority = entry.get("priority", DEFAULT_PRIORITY)
    if not isinstance(priority, str) or not priority:
        raise ValueError(f"entry #{index}: priority must be a non-empty string")
    acceptance = entry.get("acceptance", "")
    if not isinstance(acceptance, str):
        raise ValueError(f"entry #{index}: acceptance must be a string")
    for key in (
        "invariant",
        "bypass_check",
        "deletes",
        "bypass_exempt",
        "gate_lifecycle",
    ):
        if key in entry and entry[key] is not None:
            if key == "deletes":
                v = entry[key]
                if not isinstance(v, list) or not all(isinstance(x, str) and x for x in v):
                    raise ValueError(f"entry #{index}: deletes must be a list of regex strings")
            elif not isinstance(entry[key], str) or not entry[key].strip():
                raise ValueError(f"entry #{index}: {key} must be a non-empty string")
    gate_lifecycle = entry.get("gate_lifecycle", "historical-receipt")
    if gate_lifecycle not in GATE_LIFECYCLES:
        raise ValueError(
            f"entry #{index}: gate_lifecycle must be one of "
            f"{', '.join(sorted(GATE_LIFECYCLES))}"
        )
    # Deliverable-count lock (prd-fable-discipline-2026-07-04): every generated
    # spec promises an explicit deliverable count; kipi-dsse close refuses
    # until that many boxes are checked. Optional keys: `deliverables` (list of
    # strings) and/or `deliverables_count` (int >= 1); both present must agree.
    deliverables = entry.get("deliverables")
    def _is_single_line(value: str) -> bool:
        # same line-boundary semantics as issue_runner's checkbox counter
        # (str.splitlines covers \n, \r, \u2028 and every other Unicode
        # line boundary); a multi-line value would inject extra checkbox
        # lines into the generated section
        return len(value.splitlines()) == 1

    if deliverables is not None and (
        not isinstance(deliverables, list)
        or not deliverables
        or not all(
            isinstance(d, str) and d.strip() and _is_single_line(d)
            for d in deliverables
        )
    ):
        raise ValueError(
            f"entry #{index}: deliverables must be a non-empty list of "
            "single-line non-empty strings"
        )
    raw_count = entry.get("deliverables_count")
    if raw_count is not None and (
        isinstance(raw_count, bool) or not isinstance(raw_count, int) or raw_count < 1
    ):
        raise ValueError(
            f"entry #{index}: deliverables_count must be an integer >= 1"
        )
    if deliverables is not None and raw_count is not None and raw_count != len(deliverables):
        raise ValueError(
            f"entry #{index}: deliverables_count ({raw_count}) does not match "
            f"the deliverables list ({len(deliverables)} item(s))"
        )
    if deliverables is not None:
        resolved_deliverables = [d.strip() for d in deliverables]
    elif raw_count is not None:
        resolved_deliverables = [f"deliverable {i + 1}" for i in range(raw_count)]
    else:
        resolved_deliverables = [title.strip()]
    # uniform post-resolution guard: the title fallback goes through the same
    # single-line validation as explicit deliverables (codex adversarial:
    # a multi-line title injected a checked box while count stayed 1)
    if not all(_is_single_line(d) for d in resolved_deliverables):
        raise ValueError(
            f"entry #{index}: a deliverable resolved to a multi-line string "
            "(check the title); single-line only"
        )
    # the counter reads the FIRST column-0 '## Deliverables' section, so
    # free-form acceptance text must not smuggle one in above the generated
    # section (codex adversarial: acceptance hijacked the count)
    if any(
        line.strip().lower().startswith("## deliverables")
        for line in acceptance.splitlines()
    ):
        raise ValueError(
            f"entry #{index}: acceptance must not contain a '## Deliverables' "
            "heading; that section is generated and counted at close"
        )

    return {
        "id": issue_id,
        "title": title.strip(),
        "finding_id": finding_id.strip(),
        "deliverables": resolved_deliverables,
        "priority": priority,
        "allowed_files": list(entry["allowed_files"]),
        "disallowed_files": list(entry.get("disallowed_files", [])),
        "required_checks": list(entry["required_checks"]),
        "required_reviews": list(entry.get("required_reviews", [])),
        "acceptance": acceptance,
        # Spine contract fields (prd-os-spine-native) — verbatim passthrough
        # into the issue spec so dsse closeout can enforce them.
        "invariant": entry.get("invariant", ""),
        "bypass_check": entry.get("bypass_check", ""),
        "gate_lifecycle": gate_lifecycle,
        "deletes": list(entry.get("deletes", [])),
        "bypass_exempt": entry.get("bypass_exempt", ""),
    }


def _validate_manifest(raw: str) -> list[dict]:
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ValueError(f"issues manifest is not valid JSON: {exc}") from exc
    if not isinstance(data, list):
        raise ValueError("issues manifest must be a JSON array")
    seen_ids: set[str] = set()
    entries: list[dict] = []
    for i, item in enumerate(data):
        entry = _validate_entry(item, i)
        if entry["id"] in seen_ids:
            raise ValueError(f"duplicate issue id within manifest: {entry['id']!r}")
        seen_ids.add(entry["id"])
        entries.append(entry)
    return entries


# ---------------------------------------------------------------------------
# Issue spec rendering
# ---------------------------------------------------------------------------


def _yaml_list(values: list[str]) -> str:
    """Render a YAML list suitable for the template placeholder.

    Empty list -> ` []` (inline). Non-empty -> newline + two-space indented
    `  - value` lines. The template places this immediately after the key's
    colon, so the leading newline/space is part of the rendered block.
    """
    if not values:
        return " []"
    return "\n" + "\n".join(f"  - {v}" for v in values)


def _render_spec(
    entry: dict,
    parent_prd_id: str,
    parent_prd_relpath: str,
    marker: str,
) -> str:
    template = TEMPLATE_RELPATH.read_text()
    rendered = (
        template.replace("{{id}}", entry["id"])
        .replace("{{title}}", entry["title"])
        .replace("{{priority}}", entry["priority"])
        .replace("{{parent_prd}}", parent_prd_id)
        .replace("{{parent_prd_path}}", parent_prd_relpath)
        .replace("{{allowed_files_yaml}}", _yaml_list(entry["allowed_files"]))
        .replace("{{disallowed_files_yaml}}", _yaml_list(entry["disallowed_files"]))
        .replace("{{required_checks_yaml}}", _yaml_list(entry["required_checks"]))
        .replace("{{required_reviews_yaml}}", _yaml_list(entry["required_reviews"]))
        .replace("{{acceptance}}", entry["acceptance"] or "<!-- fill in -->")
    )
    # Spine contract fields: append to frontmatter (template-independent so
    # old templates keep working).
    extra = []
    if entry.get("invariant"):
        extra.append(f"invariant: {json.dumps(entry['invariant'])}")
    if entry.get("bypass_check"):
        extra.append(f"bypass_check: {json.dumps(entry['bypass_check'])}")
        extra.append(f"gate_lifecycle: {entry['gate_lifecycle']}")
    if entry.get("deletes"):
        extra.append("deletes:" + _yaml_list(entry["deletes"]))
    if entry.get("bypass_exempt"):
        extra.append(f"bypass_exempt: {json.dumps(entry['bypass_exempt'])}")
    deliverables = entry.get("deliverables") or [entry["title"]]
    extra.append(f"deliverables_count: {len(deliverables)}")
    if extra:
        end = rendered.find("\n---", 3)
        rendered = rendered[:end] + "\n" + "\n".join(extra) + rendered[end:]
    boxes = "\n".join(f"- [ ] {d}" for d in deliverables)
    rendered = rendered.rstrip("\n") + (
        "\n\n## Deliverables\n\n"
        "<!-- Check each box when it ships; close refuses until checked count"
        " equals deliverables_count (locked at issue-start). -->\n"
        f"{boxes}\n"
    )
    return _inject_marker(rendered, marker)


def _inject_marker(rendered: str, marker: str) -> str:
    """Insert the marker as the first non-empty line after frontmatter close."""
    if not rendered.startswith("---"):
        # Template is malformed; bail rather than silently emit an unmarked spec.
        raise ValueError("issue template missing frontmatter")
    end = rendered.find("\n---", 3)
    if end == -1:
        raise ValueError("issue template frontmatter not closed")
    # Split at the newline AFTER the closing ---.
    nl_after = rendered.find("\n", end + len("\n---"))
    if nl_after == -1:
        prefix = rendered
        suffix = ""
    else:
        prefix = rendered[: nl_after + 1]
        suffix = rendered[nl_after + 1:]
    return prefix + marker + "\n\n" + suffix.lstrip("\n")


# ---------------------------------------------------------------------------
# Linear Definition of Ready -> issue spec (ASK-214)
# ---------------------------------------------------------------------------

# `ASK-214`. Uppercase team key + number, which is also the spec filename, so
# the pattern doubles as the path-traversal guard.
LINEAR_ISSUE_ID_RE = re.compile(r"^[A-Z][A-Z0-9]{0,9}-\d+$")
LINEAR_PRD_PREFIX = "linear:"
LINEAR_FINDING_ID = "linear-dor"
LINEAR_ISSUE_URL = "https://linear.app/ask-consulting/issue/{id}"

_DOR_HEADING_RE = re.compile(r"(?mi)^#{1,6}\s*Definition of Ready\s*$")
_HEADING_RE = re.compile(r"^#{1,6}\s+\S")
# `- **Files:** ...`, `* **Files:** ...`, or a bare `**Files:**` line. Linear
# renders bullets as `*`, the drafter prompt writes `-`; accept both.
_LABEL_LINE_RE = re.compile(
    r"^\s*(?:[-*+]\s+)?\*\*\s*([A-Za-z][A-Za-z ]*?)\s*:?\s*\*\*:?\s*(.*)$"
)
# A DoR that says the paths are unknown is the class that already burns
# dispatches: no `Files:` means no diff, so converge exits on an empty PR.
# Refuse loudly here instead of emitting a spec with empty allowed_files,
# which would make `issue_runner.py scope` meaningless.
_UNKNOWN_RE = re.compile(
    r"\b(unknown|needs?\s+a\s+recon|recon\s+pass|tbd|to\s+be\s+determined|n/a)\b",
    re.IGNORECASE,
)
# A path token: no whitespace, no shell/markdown punctuation.
_PATH_TOKEN_RE = re.compile(r"[A-Za-z0-9_.][A-Za-z0-9_.\-/]*")


class LinearDoRError(Exception):
    """The DoR cannot produce a valid spec. Always names the issue."""


def _dor_section(description: str) -> Optional[str]:
    """The `## Definition of Ready` body, up to the next heading."""
    m = _DOR_HEADING_RE.search(description)
    if not m:
        return None
    rest = description[m.end():]
    nxt = re.search(r"(?m)^#{1,6}\s+\S", rest)
    return rest[: nxt.start()] if nxt else rest


def _dor_fields(section: str) -> dict:
    """Map lowercased DoR labels to their raw values.

    A value runs from its `**Label:**` line until the next labelled line, a
    blank line, or a heading. That covers both shapes the drafter emits: one
    bullet per line, and a bullet whose paths wrap onto indented continuations.
    """
    fields: dict = {}
    current: Optional[str] = None
    buf: list[str] = []

    def _flush() -> None:
        nonlocal current, buf
        if current is not None and current not in fields:
            fields[current] = "\n".join(buf).strip()
        current, buf = None, []

    for line in section.splitlines():
        if _HEADING_RE.match(line):
            break
        m = _LABEL_LINE_RE.match(line)
        if m:
            _flush()
            current = m.group(1).strip().lower()
            buf = [m.group(2)]
            continue
        if current is None:
            continue
        if not line.strip():
            _flush()
            continue
        buf.append(line)
    _flush()
    return fields


def _split_candidates(value: str) -> list[str]:
    """Backticked spans when present, else comma/newline-separated chunks.

    Backticks win because every DoR that bothers to mark code marks the paths,
    and prose in the same bullet ("merging PR #23") must not become a path.
    """
    ticked = re.findall(r"`([^`]+)`", value)
    if ticked:
        return ticked
    return re.split(r"[,\n;]", value)


def _extract_paths(value: str) -> list[str]:
    """Every path-shaped token in a DoR bullet, order-preserving and deduped."""
    out: list[str] = []
    seen: set[str] = set()
    for raw in _split_candidates(value):
        token = raw.strip()
        # trailing annotations the drafter adds: "(new)", "(one line)"
        token = re.sub(r"\s*\([^()]*\)\s*$", "", token).strip()
        token = token.strip("`*_ \t").rstrip(".,;:")
        if not token or not _PATH_TOKEN_RE.fullmatch(token):
            continue
        # a bare word with no separator and no extension is prose, not a path
        if "/" not in token and "." not in token:
            continue
        if token not in seen:
            seen.add(token)
            out.append(token)
    return out


def _as_disallowed(paths: list[str]) -> list[str]:
    """Deny patterns for `issue_runner.py scope`, which fnmatches repo-relative
    paths. A bare basename (`converge.sh`) would then only match a file at the
    repo root, i.e. never -- a decorative deny. Ambiguity resolves toward MORE
    blocking, so a basename becomes `**/<name>`. allowed_files gets no such
    widening: there the same ambiguity has to resolve toward a loud scope block,
    never toward silently granting a wider write surface.
    """
    return [p if "/" in p else f"**/{p}" for p in paths]


def _flatten(text: str) -> str:
    """One line, collapsed whitespace -- YAML list items are line-delimited."""
    return " ".join(text.split())


def _entry_from_dor(issue_id: str, title: str, description: str) -> dict:
    """Build a manifest entry from a Linear issue's Definition of Ready.

    Field mapping (settled in ASK-214, matching linear-dor-drafter.py's prompt):
      **Files:**     -> allowed_files
      **Not doing:** -> disallowed_files
      **Check:**     -> required_checks
      **Outcome:**   -> the `## Acceptance` body
    """
    section = _dor_section(description or "")
    if section is None:
        raise LinearDoRError(
            f"{issue_id}: no '## Definition of Ready' section in the issue "
            "description. The worker only dispatches issues that have one; "
            "add a DoR (linear-dor-drafter.py writes them) and re-run."
        )
    fields = _dor_fields(section)

    files_value = fields.get("files", "")
    if not files_value:
        raise LinearDoRError(
            f"{issue_id}: DoR has no '**Files:**' line, so allowed_files would "
            "be empty and `issue_runner.py scope` would enforce nothing. "
            "Name the paths in the DoR and re-run."
        )
    if _UNKNOWN_RE.search(files_value):
        raise LinearDoRError(
            f"{issue_id}: DoR '**Files:**' says the paths are unknown "
            f"({_flatten(files_value)[:120]!r}). An issue with no known files "
            "cannot produce a diff; do the recon pass first, then re-run."
        )
    allowed = _extract_paths(files_value)
    if not allowed:
        raise LinearDoRError(
            f"{issue_id}: DoR '**Files:**' names no path-shaped token "
            f"({_flatten(files_value)[:120]!r}). Write explicit repo-relative "
            "paths and re-run."
        )

    check_value = fields.get("check", "")
    checks = [_flatten(c) for c in _split_candidates(check_value)]
    checks = [c for c in checks if c and not c.startswith("#")]
    if not checks:
        raise LinearDoRError(
            f"{issue_id}: DoR has no runnable '**Check:**' command, so "
            "required_checks would be empty and the verify receipt would prove "
            "nothing. Name the command that fails today and re-run."
        )

    disallowed = _as_disallowed(_extract_paths(fields.get("not doing", "")))
    # `scope` tests disallowed BEFORE allowed, so a path in both would deny the
    # very files the issue must edit. That is a contradictory DoR, not something
    # to silently resolve.
    conflict = [p for p in disallowed if p in allowed or p.lstrip("*/") in allowed]
    if conflict:
        raise LinearDoRError(
            f"{issue_id}: DoR lists {', '.join(conflict)} under both "
            "'**Files:**' and '**Not doing:**'. scope denies before it allows, "
            "so that spec would block its own work. Fix the DoR and re-run."
        )

    outcome = fields.get("outcome", "").strip()
    return {
        "id": issue_id,
        "title": _flatten(title) or issue_id,
        "finding_id": LINEAR_FINDING_ID,
        "allowed_files": allowed,
        "disallowed_files": disallowed,
        "required_checks": checks,
        "acceptance": outcome or "<!-- fill in -->",
    }


def _fetch_linear_issue(cfg: Config, issue_id: str) -> dict:
    """The issue payload from Linear, via the fleet's own client.

    No private copy of the auth/transport convention: linear-sync.py owns it and
    this imports that module by path, the same way pr-receipt-gate.py imports
    linear_branch.py rather than carrying its own regex. A missing client is a
    hard error, not a silent fallback.
    """
    import importlib.util

    client_path = cfg.repo_root / "q-system/.q-system/scripts/linear-sync.py"
    if not client_path.is_file():
        raise LinearDoRError(
            f"{issue_id}: no Linear client at {client_path}. Pass "
            "--linear-json <path> with the issue payload instead."
        )
    spec = importlib.util.spec_from_file_location("kipi_linear_sync", client_path)
    module = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(module)
        data = module.graphql(
            "query($id: String!) { issue(id: $id) "
            "{ identifier title description } }",
            {"id": issue_id},
        )
    except Exception as exc:  # transport, auth, GraphQL — all fatal here
        raise LinearDoRError(f"{issue_id}: Linear fetch failed: {exc}") from exc
    issue = (data or {}).get("issue")
    if not isinstance(issue, dict):
        raise LinearDoRError(f"{issue_id}: Linear returned no such issue")
    return issue


def _load_linear_payload(cfg: Config, issue_id: str, json_path: Optional[str]) -> dict:
    """The issue payload, from a file when given, else live from Linear.

    --linear-json is a transport seam (offline runs and hermetic tests), not a
    provenance seam: prd_split.py is still the only thing that renders and marks
    a spec, so the marker's claim stays true either way.
    """
    if not json_path:
        return _fetch_linear_issue(cfg, issue_id)
    path = Path(json_path)
    try:
        payload = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        raise LinearDoRError(f"{issue_id}: cannot read {path}: {exc}") from exc
    if not isinstance(payload, dict):
        raise LinearDoRError(f"{issue_id}: {path} must hold a JSON object")
    return payload.get("issue") if isinstance(payload.get("issue"), dict) else payload


def _split_from_linear(cfg: Config, args: argparse.Namespace) -> int:
    issue_id = args.from_linear.strip()
    if not LINEAR_ISSUE_ID_RE.match(issue_id):
        sys.stderr.write(
            f"--from-linear expects a Linear issue id like ASK-214 "
            f"(pattern {LINEAR_ISSUE_ID_RE.pattern!r}); got {issue_id!r}\n"
        )
        return 2
    try:
        payload = _load_linear_payload(cfg, issue_id, args.linear_json)
        entry = _entry_from_dor(
            issue_id,
            str(payload.get("title") or ""),
            str(payload.get("description") or ""),
        )
        entry = _validate_entry(entry, 0, id_re=LINEAR_ISSUE_ID_RE)
    except LinearDoRError as exc:
        sys.stderr.write(f"{exc}\n")
        return 2
    except ValueError as exc:
        sys.stderr.write(f"{issue_id}: {exc}\n")
        return 2

    prd_id = f"{LINEAR_PRD_PREFIX}{issue_id}"
    target = cfg.issues_dir / f"{issue_id}.md"
    at_iso = _extract_existing_marker_timestamp(target) or _now_iso()
    marker = _format_marker(prd_id, entry["finding_id"], at_iso)
    rendered = _render_spec(
        entry, prd_id, LINEAR_ISSUE_URL.format(id=issue_id), marker
    )

    if target.exists() and target.read_text() != rendered:
        sys.stderr.write(f"refusing to clobber existing issue spec: {target}\n")
        return 2

    if args.dry_run:
        print(json.dumps({
            "prd_id": prd_id,
            "would_create": [] if target.exists() else [str(target)],
            "skipped_existing_identical": [str(target)] if target.exists() else [],
        }, indent=2))
        return 0

    created: list[str] = []
    if not target.exists():
        cfg.issues_dir.mkdir(parents=True, exist_ok=True)
        target.write_text(rendered)
        created.append(
            str(target.relative_to(cfg.repo_root))
            if target.is_absolute() and str(target).startswith(str(cfg.repo_root))
            else str(target)
        )
    print(json.dumps({"prd_id": prd_id, "created": created}, indent=2))
    return 0


# ---------------------------------------------------------------------------
# PRD resolution
# ---------------------------------------------------------------------------


def _resolve_prd_path(cfg: Config, prd_id: Optional[str]) -> tuple[str, Path]:
    if prd_id:
        path = cfg.prds_dir / f"{prd_id}.md"
        if not path.is_file():
            raise ValueError(f"PRD spec not found: {path}")
        return prd_id, path
    # Fall back to active PRD state.
    state_path = cfg.active_prd_state_path
    if not state_path.is_file():
        raise ValueError(
            "no --prd-id given and no active PRD state. Load or create a PRD first."
        )
    try:
        state = json.loads(state_path.read_text())
    except json.JSONDecodeError as exc:
        raise ValueError(f"{state_path}: invalid JSON ({exc})") from exc
    active_id = state.get("prd_id")
    spec_path_rel = state.get("spec_path")
    if not active_id or not spec_path_rel:
        raise ValueError("active PRD state is empty; pass --prd-id explicitly")
    path = cfg.repo_root / spec_path_rel
    if not path.is_file():
        raise ValueError(f"active PRD spec missing on disk: {path}")
    return active_id, path


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", help="override repo root discovery")
    parser.add_argument("--prd-id", help="PRD id; defaults to active PRD state")
    parser.add_argument(
        "--dry-run", action="store_true", help="validate and print planned writes; do not touch disk"
    )
    parser.add_argument(
        "--from-linear",
        metavar="ASK-n",
        help="generate one spec from a Linear issue's Definition of Ready "
             "instead of from an approved PRD",
    )
    parser.add_argument(
        "--linear-json",
        metavar="PATH",
        help="read the --from-linear issue payload from a JSON file "
             "(offline/test transport) instead of calling Linear",
    )
    args = parser.parse_args(argv)

    try:
        repo_root = Path(args.repo_root).resolve() if args.repo_root else None
        cfg = load_config(repo_root, strict=True)
    except ConfigError as exc:
        sys.stderr.write(f"prd-os config error: {exc}\n")
        return 2

    # Branch BEFORE PRD resolution so no pre-existing invocation changes shape.
    # `is not None`, not truthiness: `--from-linear ''` was passed explicitly and
    # must be refused as a bad id, never fall through to the PRD path.
    if args.from_linear is not None:
        if args.prd_id:
            sys.stderr.write(
                "--from-linear and --prd-id are mutually exclusive: a Linear "
                "issue has no parent PRD.\n"
            )
            return 2
        return _split_from_linear(cfg, args)
    if args.linear_json:
        sys.stderr.write("--linear-json requires --from-linear\n")
        return 2

    try:
        prd_id, prd_path = _resolve_prd_path(cfg, args.prd_id)
    except ValueError as exc:
        sys.stderr.write(f"{exc}\n")
        return 2

    text = prd_path.read_text()
    try:
        fm, body_start = _parse_frontmatter(text)
    except ValueError as exc:
        sys.stderr.write(f"{prd_path}: {exc}\n")
        return 2
    status = fm.get("status")
    if status != "approved":
        sys.stderr.write(
            f"refusing to split PRD with status={status!r}. "
            "Only approved PRDs may be split.\n"
        )
        return 2
    parent_prd_id = fm.get("id", prd_id)

    try:
        raw_manifest = _extract_issues_block(text[body_start:])
        entries = _validate_manifest(raw_manifest)
    except ValueError as exc:
        sys.stderr.write(f"{prd_path}: {exc}\n")
        return 2
    if not entries:
        sys.stderr.write(f"{prd_path}: issues manifest is empty; nothing to split\n")
        return 2

    try:
        parent_prd_relpath = str(prd_path.resolve().relative_to(cfg.repo_root))
    except ValueError:
        parent_prd_relpath = str(prd_path)

    planned: list[tuple[Path, str]] = []
    collisions: list[str] = []
    for entry in entries:
        target = cfg.issues_dir / f"{entry['id']}.md"
        # Reuse any existing marker timestamp so reruns stay byte-identical.
        existing_at = _extract_existing_marker_timestamp(target)
        at_iso = existing_at or _now_iso()
        marker = _format_marker(parent_prd_id, entry["finding_id"], at_iso)
        rendered = _render_spec(entry, parent_prd_id, parent_prd_relpath, marker)
        if target.exists():
            existing = target.read_text()
            if existing != rendered:
                collisions.append(str(target))
                continue
            # byte-identical: idempotent re-run, skip
            continue
        planned.append((target, rendered))

    if collisions:
        sys.stderr.write(
            "refusing to clobber existing issue spec(s):\n  - "
            + "\n  - ".join(collisions)
            + "\n"
        )
        return 2

    if args.dry_run:
        print(json.dumps(
            {
                "prd_id": parent_prd_id,
                "would_create": [str(p) for p, _ in planned],
                "skipped_existing_identical": [
                    str(cfg.issues_dir / f"{e['id']}.md")
                    for e in entries
                    if (cfg.issues_dir / f"{e['id']}.md").exists()
                ],
            },
            indent=2,
        ))
        return 0

    cfg.issues_dir.mkdir(parents=True, exist_ok=True)
    created: list[str] = []
    for target, rendered in planned:
        target.write_text(rendered)
        created.append(str(target.relative_to(cfg.repo_root)) if target.is_absolute() else str(target))
    print(json.dumps({"prd_id": parent_prd_id, "created": created}, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
