#!/usr/bin/env python3
"""design-chain-gate: web design work cannot be shown, tested, sent or left behind
until the agreed design steps have produced their receipts.

WHY (founder, 2026-09-15, after two rounds of first screens ignored the canon):
  "When I try to create web design, you continuously find ways to go back to your
  generic stuff. If it's not reading the prose, ignoring the prose, or going around it."
  A lint on the page is a blocklist and was rejected. This is the other shape: a
  chain of receipts the harness demands before the next tool call can happen.

THE THREE HOLES THIS CLOSES (each one was used the same day):
  1. Pages generated by a script (build2.py wrote six .html files) never hit the
     Write hook. So the ledger is fed by a filesystem scan after every Bash call,
     not by the Write tool alone.
  2. Pages built outside design-room/ never hit publish_gate. So there is no path
     scope: any page file anywhere (except the internal allowlist) is in scope.
  3. A brief written from memory is how the generic layout comes back. So the brief
     must contain lines extracted LIVE from the owner files, verbatim.

WHAT IT DOES NOT BLOCK (2026-09-15): the chain's own steps. Measuring, serving,
screenshotting and sealing a page are how the chain CLOSES; blocking them made the
command unrunnable. See BASH_SHOW_RE below.

THE CHAIN, per page, in the round directory that holds the page:
  brief.md        verbatim anchors from the owner files + the three-line brief
  directions.md   three directions; cites an exemplar when exemplars/ is non-empty
  standard.json   written by design-standard-check.py: pass true, sha256 of the page
  critique.md     the nine DNA questions answered per direction
  proof.md        each artifact's proof kind and its INDEX record
  checks/         bio_gate + voice-lint outputs
  gate/           ICP-persona comprehension answers
  receipts.json   written by `seal`; sha256 per page; stale on any later edit

HOOK CONTRACT: reads the hook JSON on stdin, keys on hook_event_name and tool_name.
exit 0 = pass, exit 2 = block (stderr goes to the model). `seal` and `status` are CLI
subcommands. Fails OPEN only when the payload itself is unreadable; every ambiguity
about a page in the ledger fails CLOSED.

OVERRIDE: DESIGN_CHAIN_ALLOW=1 in the founder's shell. No in-file marker exists, on
purpose: a marker the agent can write is not an override, it is a hole.

HONEST BOUNDARY: the scan after a Bash call covers the Bash cwd, the project dir, the
scratchpad and the registered instance roots. A page written somewhere else by a
script is not seen until it is sent or opened by a tool this gate watches.

stdlib only. Self-test: test_design_chain_gate.py.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
import sys
import time
from html.parser import HTMLParser
from pathlib import Path

PAGE_EXTS = {".html", ".htm", ".astro", ".jsx", ".tsx", ".vue", ".svelte"}
# Internal HTML the founder alone sees. A path segment match, not a marker in the file.
INTERNAL_MARKERS = (
    "/node_modules/", "/.git/", "/dist/", "/build/", "/.next/", "/coverage/",
    "daily-schedule", "morning-log", "/logs/", "/log/", "/test", "/tests/", "/fixtures/",
    "/schedule", "/dashboard", "/report", "/vendor/", "/site-packages/", "/.playwright-mcp/",
    "/exemplars/",
)
CHAIN_FILES = ("brief.md", "directions.md", "standard.json", "critique.md", "proof.md")
CHAIN_DIRS = ("checks", "gate")
# The BAR half, switched on per instance by a `craft` block in design-chain.json.
# Everything above this line is a FLOOR: it sees missing files, unquoted anchors, word
# counts and type sizes. A round cleared all of it on 2026-09-15 while shipping three
# wireframes with no imagery, no motion and no depth -- the failure
# q-system/lessons/a-defect-absence-gate-is-a-floor-not-a-finish-line.md already named,
# distilled from cole-gtm rca-design-room-skipped-premium-tools-2026-06-25. Its four
# causes, all of which recurred: a floor-detector became the definition of done;
# grounding enforced provenance, not ambition; the direction was resolved at concept
# level with no execution tier, so premium and floor realizations were equally
# compliant; effort-economy ran downhill to the cheapest passing artifact.
CRAFT_MANIFEST = "craft-manifest.json"
GAP_CHECK = "gap.json"
# A weakness the author wrote down and then shipped anyway. Measured 2026-09-15 across
# three sealed rounds: 11 findings marked WEAK in critique.md, 0 required an answer, and
# two of them were the exact defects the founder and the reader gate then caught. The
# critique step was producing findings into a file nothing read back.
# A decision handed to the founder and buried in a file he does not open. Same class as
# the WEAK finding above, found by sweeping for it: "founder decision" / "founder question"
# appeared 9 times across the chain's artifacts on 2026-09-15 with no executable reading
# any of them back, while {{UNVALIDATED}} and {{NEEDS_PROOF}} both have blocking linters.
# The ones the founder answered, he answered because they came up in conversation.
# A gate cannot make him decide. It CAN refuse to let a question be raised and buried.
FOUNDER_RE = re.compile(r"\bFOUNDER\[([a-z0-9][a-z0-9-]*)\]")
OPEN_DECISIONS = "OPEN-DECISIONS.md"
WEAK_RE = re.compile(r"\bWEAK(?:EST)?\b(?:\[([a-z0-9][a-z0-9-]*)\])?")
DISPOSITION_RE = re.compile(r"^\s*[-*]\s*([a-z0-9][a-z0-9-]*)\s*:\s*(FIXED|DEFERRED|CARRIED)\b(.*)$",
                            re.M)
IMPECCABLE_CHECK = "impeccable.txt"
# Bash commands that put a page in front of a HUMAN. Blocked while the chain is open.
#
# WHY this list is short (2026-09-15, found the first time the command was run end to
# end): it used to also carry screenshot|playwright|http.server|shoot*.py|gate*.py|
# comprehension, and the branch below additionally blocked any command merely NAMING an
# open page. Those are the chain's own steps -- design-standard-check.py writes
# standard.json (step 5), the serve it measures against, shoot + gate_icp (step 9) and
# `seal` itself (step 10). The gate blocked every step of the command it enforces, so a
# chain opened by an agent could never be closed by one. Rendering a page to MEASURE it
# is not showing it; the surfaces that reach the founder (SendUserFile, Artifact, the
# browser MCP tools) and the Stop hook are unchanged and still block.
# Catches a command that SHOWS a page, and nothing else. It has over-matched twice:
#   1. on the chain's OWN steps, because it matched this file's name and any command
#      naming a page (fixed 2026-09-15, kipi-system 9c7293c3)
#   2. on PROSE: a heredoc carrying the word o-p-e-n in a sentence, with a page filename
#      many lines later in the same command, matched because [^|;&] also matches a
#      newline. Blocked a craft-manifest write that showed nothing (2026-09-15)
# So the verb now has to sit where a command sits (start of the string, or after a pipe,
# semicolon, ampersand or newline) and the filename has to be on the SAME line as it.
BASH_SHOW_RE = re.compile(
    r"(?:^|[|;&\n]\s*)(?:open\s+-a\b|open\s+[^|;&\n]*\.(?:html?|png|jpe?g|pdf)\b"
    r"|vercel\s+deploy\b)", re.I)
SHOW_TOOLS_PREFIX = ("mcp__playwright__", "mcp__claude-in-chrome__", "mcp__plugin_chrome-devtools")
PUBLISH_TOOLS = ("SendUserFile", "Artifact")
NINE_QUESTIONS = 9
STATE_DIR = Path(os.environ.get("DESIGN_CHAIN_STATE", os.path.expanduser("~/.config/kipi/design-chain")))
CONFIG_NAME = "design-chain.json"


# ---------------------------------------------------------------- helpers

def _norm(s: str) -> str:
    return re.sub(r"\s+", " ", s).strip().lower()


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


# ---------------------------------------------------------------- producers
#
# `seal` used to READ standard.json and checks/gap.json as trusted inputs, so a verdict
# typed by hand sealed a round (RCA rca-design-chain-trusts-its-own-account-2026-09-18,
# C3 and C7: round A sealed at exit 0). It now RUNS the producers and uses their exit
# codes. The files they write are outputs of this run, not claims handed to it.
#
# Producers are the siblings of THIS file and nothing else. There is deliberately no
# environment variable, flag or path condition that points seal at another directory
# (Sana, 2026-09-18: any override production can honor is the gate trusting an account of
# itself again). Tests get stand-ins by running a COPY of this file placed beside them,
# and test_dc_seal_runs_producers.py goes red if an override token appears here.
HERE = Path(__file__).resolve().parent
STANDARD_PRODUCER = "design-standard-check.py"
GAP_PRODUCER = "design-gap-check.py"
PRODUCER_TIMEOUT_S = 600


def clean_env() -> dict:
    """The child's environment with every PYTHON* variable removed.

    Adversarial review of c598d5f5, reproduced against the installed gate: a sitecustomize.py
    on PYTHONPATH made the real producer exit 0 before it measured anything. The child also
    runs with -E, which makes the interpreter ignore those variables even if one survives.

    THE TRADEOFF, stated because it is real: -E ignores PYTHONUSERBASE too, so a producer
    dependency installed with `pip install --user` under a NON-DEFAULT user base (a CI
    container with a read-only HOME) is not importable in the child, and seal says "could
    not measure". Letting the variable through buys nothing (-E ignores it) and the refusal
    message names it. WHAT THIS DOES NOT CLOSE: -E leaves the DEFAULT user site enabled, so a
    usercustomize.py there is still imported at child startup (measured by Sana, 2026-09-18).
    Running the child with -s closes that and is dc-03's, with its own test."""
    return {k: v for k, v in os.environ.items() if not k.upper().startswith("PYTHON")}


def run_producer(name: str, args: list[str]) -> tuple[int, str]:
    """(exit code, tail of output). A producer that is missing, hangs or cannot start is
    exit 2: it could not measure, and could-not-measure is never a pass."""
    script = HERE / name
    if not script.is_file():
        return 2, f"could not measure: producer missing at {script}"
    try:
        r = subprocess.run([sys.executable, "-E", str(script), *args], capture_output=True,
                           text=True, timeout=PRODUCER_TIMEOUT_S, env=clean_env())
    except subprocess.TimeoutExpired:
        return 2, f"could not measure: {name} timed out after {PRODUCER_TIMEOUT_S}s"
    except OSError as e:
        return 2, f"could not measure: {name} did not start: {e}"
    tail = " | ".join((r.stdout + r.stderr).strip().splitlines()[-4:])
    if "ModuleNotFoundError" in tail:
        tail += (" | the producer child runs with -E and no PYTHON* variables, so PYTHONUSERBASE "
                 "is ignored: install the dependency where the default site can see it")
    return r.returncode, tail


def _mtime_ns(path: Path) -> int:
    try:
        return path.stat().st_mtime_ns
    except OSError:
        return -1


def _fresh_standard_entry(std_path: Path, before_ns: int, page: Path) -> dict | None:
    """The entry the producer wrote for THIS page during THIS run, or None.

    An exit code is a claim. The verdict is the file the producer writes, so it has to have
    been rewritten after the run started and carry this page's current bytes. ASSUMPTION:
    st_mtime_ns strictly increases between two writes, true on APFS (0 false refusals in 120
    checks, review of c6696467) and wrong in principle on 1-second filesystems. dc-03 makes
    seal remove the page's prior entry before the run, so mtime becomes a cross-check. A producer that
    exits 0 having written nothing (hijacked, or crashed past its own handler) returns None,
    and a verdict typed by hand before the run is older than the run."""
    if _mtime_ns(std_path) <= before_ns:
        return None
    try:
        data = json.loads(std_path.read_text())
    except (OSError, ValueError):
        return None
    cur = sha(page)
    for e in (data if isinstance(data, list) else [data]):
        if isinstance(e, dict) and e.get("page") == page.name and e.get("sha256") == cur:
            return e
    return None


def round_declaration(rd: Path) -> dict:
    mp = rd / CRAFT_MANIFEST
    if not mp.is_file():
        return {}
    try:
        d = json.loads(mp.read_text())
    except ValueError:
        return {}
    return d if isinstance(d, dict) else {}


def producer_problems(rd: Path, pages: list[Path], cfg: dict) -> list[tuple[str, list[str]]]:
    """Run the producers for a round. Returns (name, problems) pairs in seal's `bad` shape."""
    bad: list[tuple[str, list[str]]] = []
    std_path = rd / "standard.json"
    for p in pages:
        before = _mtime_ns(std_path)
        rc, tail = run_producer(STANDARD_PRODUCER, [str(p)])
        entry = _fresh_standard_entry(std_path, before, p)
        if rc == 0 and entry and entry.get("pass") is True:
            continue
        if rc == 1 and entry and entry.get("pass") is False:
            bad.append((p.name, [f"{STANDARD_PRODUCER} measured this page and it FAILS the standard: {tail}"]))
        else:
            # exit 2, a crash (also exit 1), or an exit code with no fresh verdict behind it
            bad.append((p.name, [f"could not measure ({STANDARD_PRODUCER} exit {rc}, "
                                 f"{'no' if not entry else 'a contradicting'} fresh verdict for this page): {tail}"]))
    craft = cfg.get("craft") or {}
    declared = round_declaration(rd)
    # The same round-local opt-out craft_problems() honors: a declared wireframe round carries
    # a written reason and is exempt from the craft bar. Measuring it anyway leaves it stuck.
    round_is_wireframe = declared.get("tier") == "wireframe" and str(declared.get("reason", "")).strip()
    if (craft.get("require_gap_check") and craft.get("tier", "craft") != "wireframe"
            and not round_is_wireframe):
        gap_path = rd / "checks" / GAP_CHECK
        before = _mtime_ns(gap_path)
        args = [str(rd), "--write"]
        url_base = (cfg.get("serve") or {}).get("url_base")
        if url_base:
            args += ["--url-base", str(url_base)]
        rc, tail = run_producer(GAP_PRODUCER, args)
        if rc == 0 and _mtime_ns(gap_path) <= before:
            bad.append((GAP_PRODUCER, [f"could not measure ({GAP_PRODUCER} exit 0 and wrote no fresh "
                                       f"{GAP_CHECK}): {tail}"]))
        elif rc != 0:
            # design-gap-check.py uses exit 2 for BOTH outcomes today. Guessing which from its
            # prose labelled every real exit 2 wrongly (the phrase this used to look for is
            # printed only by the test stand-in). One honest label until dc-03 gives the
            # producer an exit code of its own for could-not-measure (Sana, 2026-09-18).
            bad.append((GAP_PRODUCER, [f"below the exemplar floor OR could not measure ({GAP_PRODUCER} "
                                       f"exit {rc}; it uses one code for both): {tail}"]))
    return bad


def is_page(path: str) -> bool:
    p = str(Path(path).resolve()) if path else ""
    if not p or Path(p).suffix.lower() not in PAGE_EXTS:
        return False
    low = p.lower() + "/"
    return not any(m in low for m in INTERNAL_MARKERS)


def find_config(start: Path) -> Path | None:
    """Nearest design-chain.json walking up from the page, then the project dir."""
    for d in [start] + list(start.parents):
        c = d / CONFIG_NAME
        if c.is_file():
            return c
    proj = os.environ.get("CLAUDE_PROJECT_DIR")
    if proj and (Path(proj) / CONFIG_NAME).is_file():
        return Path(proj) / CONFIG_NAME
    return None


def load_config(page: Path) -> tuple[dict, Path | None]:
    c = find_config(page.parent)
    if not c:
        return {}, None
    try:
        return json.loads(c.read_text()), c
    except (OSError, ValueError):
        return {}, c


def anchors_from_owners(cfg: dict, cfg_path: Path | None) -> list[tuple[str, str]]:
    """(label, verbatim line) for every anchor, read LIVE from the owner files.
    A missing owner file or an anchor that matches nothing is itself a failure the
    caller reports: the brief cannot quote what does not exist."""
    out = []
    root = cfg_path.parent if cfg_path else Path(".")
    for own in cfg.get("owners", []):
        f = root / own["file"]
        try:
            lines = f.read_text().splitlines()
        except OSError:
            out.append((own["file"], "__MISSING_OWNER_FILE__"))
            continue
        for rx in own.get("anchors", []):
            pat = re.compile(rx)
            hit = None
            for ln in lines:
                m = pat.search(ln)
                if m:
                    # a capture group narrows the anchor to the part that must be
                    # quoted (a rule TITLE, not its 900-character paragraph)
                    hit = m.group(1) if m.groups() else ln
                    break
            out.append((f"{own['file']} :: {rx}", hit.strip() if hit else "__NO_MATCH__"))
    return out


def round_dir_for(page: Path) -> Path:
    """The round directory is the nearest ancestor (up to 3 levels) holding brief.md,
    else the page's own directory."""
    for d in [page.parent, page.parent.parent, page.parent.parent.parent]:
        if (d / "brief.md").is_file():
            return d
    return page.parent


# ---------------------------------------------------------------- the chain check

def copied_brief_problems(rd: Path) -> list[str]:
    """A brief that is a byte-copy of an earlier round's brief is a round that never read
    the owners.

    Step 1 of the command is "read the owners, in full, this session", and step 2 is to
    write a brief quoting them. The anchor check proves the brief CONTAINS the quotes; it
    cannot tell a brief that was written from one that was `cp`'d. Measured 2026-09-15:
    five consecutive rounds carried the identical brief, sha c3b247f7b6, so four of them
    did step 1 by copying a file.

    Writing the brief IS the act of reading. Copying it is the act of not reading, and it
    is the one part of that a checksum can see.
    """
    bp = rd / "brief.md"
    if not bp.is_file():
        return []
    mine = sha(bp)
    for other in sorted(p for p in rd.parent.iterdir() if p.is_dir() and p != rd):
        ob = other / "brief.md"
        if ob.is_file() and sha(ob) == mine:
            return [f"brief.md is byte-identical to {other.name}/brief.md. Step 1 is to read "
                    f"the owners in full THIS round; writing the brief is how that happens "
                    f"and copying it is how it does not. Re-read them and write this "
                    f"round's brief, even if much of it lands the same."]
    return []


def disposition_problems(rd: Path) -> list[str]:
    """Every weakness the critique names must carry an answer before the round seals.

    HONEST BOUNDARY, stated because this repo has been burned by gates that imply more
    than they check: this sees the marker `WEAK[tag]` and nothing else. A weakness written
    in prose ("this is the risk", "I have not yet tried") is invisible to it, and that is
    not a TODO -- deciding that a sentence describes a weakness is a judgment no regex
    makes. What it does close is the specific hole measured on 2026-09-15: an author who
    DOES mark a finding weak can no longer seal without saying what happened to it.
    """
    cp = rd / "critique.md"
    if not cp.is_file():
        return []
    text = cp.read_text()
    probs: list[str] = []
    # Findings are RAISED above the dispositions section and DISCUSSED inside it. Scanning
    # the whole file counted the section's own explanation of the marker as a new untagged
    # finding, which is a check firing on its own documentation.
    head = re.split(r"^##+\s*Disposition", text, maxsplit=1, flags=re.M | re.I)[0]
    tags, untagged = [], 0
    for m in WEAK_RE.finditer(head):
        # the file's own instructions explain the marker; that mention is not a finding
        line = head[head.rfind("\n", 0, m.start()) + 1: head.find("\n", m.end())]
        if "are marked WEAK" in line or "WEAK_RE" in line:
            continue
        if m.group(1):
            tags.append(m.group(1))
        else:
            untagged += 1
    if untagged:
        probs.append(f"critique.md marks {untagged} finding(s) WEAK with no tag. Write "
                     f"WEAK[some-tag] so the disposition below can answer it by name.")
    # founder questions: raised in a round, registered in ONE ledger he can read
    asks = sorted({m.group(1) for m in FOUNDER_RE.finditer(head)})
    if asks:
        ledger = rd.parent / OPEN_DECISIONS
        have = ledger.read_text() if ledger.is_file() else ""
        missing = [t for t in asks if t not in have]
        if missing:
            probs.append(
                f"critique.md raises founder question(s) {missing} that are not in "
                f"{ledger}. A question written into a round and nowhere else is a question "
                f"he never sees. Add each to the ledger with what is being asked and what "
                f"is blocked until he answers.")

    disposed = {m.group(1): (m.group(2), m.group(3).strip()) for m in DISPOSITION_RE.finditer(text)}
    for t in tags:
        if t not in disposed:
            probs.append(f"critique.md: weakness '{t}' has no disposition. Add a line "
                         f"'- {t}: FIXED <what changed> | DEFERRED <why> | CARRIED <where>'. "
                         f"A weakness you wrote down and shipped anyway is the failure this "
                         f"check exists for.")
        elif not disposed[t][1]:
            probs.append(f"critique.md: weakness '{t}' is marked {disposed[t][0]} with no "
                         f"reason. The disposition says what happened, not just that "
                         f"something did.")
    return probs


def craft_problems(rd: Path, page: Path, cfg: dict, cfg_path: Path | None) -> list[str]:
    """The bar-check. Silent unless the instance declares a `craft` block, so an
    instance that has not opted in keeps exactly the behaviour it had.

    It never certifies a page as good, and deliberately has no success message. Green
    here means ONLY "not a wireframe"; the founder's eye and five real buyer
    conversations are the bar (site-design.md section 8). That posture is borrowed
    whole from cole-gtm's check_technique_parity.py, whose docstring carries the
    founder line this all rests on: "when you have a floor, you are programmed to only
    pass the floor."
    """
    craft = cfg.get("craft") or {}
    if not craft:
        return []
    # An undeclared tier is the REQUIRED tier, never the cheap one: silence must not be
    # the easiest way out (the RCA's cause #4, effort-economy toward the cheapest pass).
    if craft.get("tier", "craft") == "wireframe":
        return []

    probs: list[str] = []
    mpath = rd / CRAFT_MANIFEST

    # A ROUND may declare itself a wireframe round, which the instance default must not
    # be flipped to do. Without this the only way to keep an honest copy-test round
    # sealed is to set craft.tier=wireframe in design-chain.json, which silently lowers
    # the bar for every future round -- the opposite of the point. A round-local
    # declaration is narrow, dated by its own directory, and has to carry a reason, so
    # it reads as a labelled exception rather than a quiet downgrade.
    if mpath.is_file():
        try:
            declared = json.loads(mpath.read_text())
        except ValueError:
            declared = {}
        # A WITHDRAWN round is one the founder has already rejected. This gate exists to
        # stop unfinished work being SHOWN, and a withdrawn round is never going to be
        # shown, so holding it to the bar only forces its author to either fake a receipt
        # or stay stuck. It still carries a reason, and it is one-way: nothing here lets a
        # round be withdrawn and then presented, because presenting it would mean writing
        # it back to a live tier in the open.
        if declared.get("status") == "withdrawn":
            if not str(declared.get("reason", "")).strip():
                return [f"{CRAFT_MANIFEST} declares status 'withdrawn' with no reason. A "
                        f"round may be withdrawn, but the record says why."]
            return []
        if declared.get("tier") == "wireframe":
            if not str(declared.get("reason", "")).strip():
                return [f"{CRAFT_MANIFEST} declares tier 'wireframe' with no reason. A "
                        f"round may opt out of the craft bar, but it says why, in "
                        f"writing, in the round."]
            return []
    if craft.get("require_craft_manifest"):
        if not mpath.is_file():
            probs.append(
                f"missing {mpath}: at tier '{craft.get('tier', 'craft')}' each direction "
                f"declares its signature moment and the technique that realizes it "
                f"(id, technique, role, reference, import[], applied[]). Without it the "
                f"research is decorative and the cheapest layout wins.")
        else:
            try:
                man = json.loads(mpath.read_text())
            except ValueError as e:
                man, probs = {}, probs + [f"{CRAFT_MANIFEST} is not valid JSON: {e}"]
            techs = man.get("techniques") or []
            if not techs:
                probs.append(f"{CRAFT_MANIFEST} declares no techniques, so nothing was "
                             f"verified. Declaring nothing must not be the cheapest way "
                             f"to comply.")
            else:
                src = page.read_text(errors="replace")
                src = re.sub(r"<!--.*?-->", " ", src, flags=re.DOTALL)
                src = re.sub(r"/\*.*?\*/", " ", src, flags=re.DOTALL)
                for t in techs:
                    if t.get("pages") and page.name not in t["pages"]:
                        continue
                    imp, app = t.get("import") or [], t.get("applied") or []
                    if not imp and not app:
                        probs.append(f"{CRAFT_MANIFEST}: technique "
                                     f"'{t.get('id', '?')}' declares no fingerprint, so it "
                                     f"cannot be verified present")
                        continue
                    missing = [p for p in imp + app if not re.search(p, src)]
                    if missing:
                        probs.append(f"{CRAFT_MANIFEST}: technique '{t.get('id', '?')}' "
                                     f"({t.get('role', '?')}) is declared but absent from "
                                     f"{page.name}: {missing}")
    # GROUNDING. The chain had an enforcement half and no input half: the manifest made
    # the build prove it used what it declared, and nothing made the declaration come from
    # anywhere but the builder's own prior. So it verified that the builder built what he
    # imagined, and passed while producing the same generic page three rounds running.
    # Founder, 2026-09-15: "This is the most generic stuff ever... do you need an example
    # to work from?" cole-gtm's design-room had the step and only its back half was ported:
    #   theirs:  ground -> teardown -> steal-manifest -> build -> parity
    #   ported:                     craft-manifest -> build -> parity
    ground = craft.get("require_grounding")
    if ground and mpath.is_file():
        tpath = (cfg_path.parent / ground) if cfg_path else Path(ground)
        if not tpath.is_file():
            probs.append(f"missing {tpath}: at tier '{craft.get('tier','craft')}' the craft "
                         f"manifest must be filled from real pages that were opened, not "
                         f"from memory. Load the references, record what makes each one "
                         f"not generic, then declare techniques that cite them.")
        else:
            teardown = tpath.read_text()
            # Every exemplar the founder has named must appear in the narrative. Founder,
            # 2026-09-15: "you should do that every time I put in more exemplars." Adding
            # a site and not re-reading the GROUP is the forgettable step, so it is a
            # blocked state instead of a promise.
            roster = tpath.parent / "exemplars.json"
            if roster.is_file():
                try:
                    named = [e.get("url", "") for e in
                             json.loads(roster.read_text()).get("exemplars", [])]
                except ValueError:
                    named = []
                host = lambda u: u.split("//")[-1].split("/")[0].lower().removeprefix("www.")
                stale = [u for u in named if host(u) and host(u) not in _norm(teardown)]
                if stale:
                    probs.append(
                        f"{tpath.name} does not read the whole exemplar set: {stale} "
                        f"{'is' if len(stale) == 1 else 'are'} in {roster.name} and absent "
                        f"from the narrative. A new exemplar changes what the others mean, "
                        f"so the group gets re-read, not appended to.")
            try:
                man = json.loads(mpath.read_text())
            except ValueError:
                man = {}
            for t in man.get("techniques") or []:
                ref = str(t.get("reference", "")).strip()
                if not ref:
                    probs.append(f"{CRAFT_MANIFEST}: technique '{t.get('id','?')}' cites no "
                                 f"reference. A technique with no source is invention.")
                elif not any(_norm(part) and _norm(part) in _norm(teardown)
                             for part in re.split(r"[+,]", ref)):
                    probs.append(f"{CRAFT_MANIFEST}: technique '{t.get('id','?')}' cites "
                                 f"'{ref}', which is not in {tpath.name}. Tear the reference "
                                 f"down there first, or the citation is decoration.")
    # THE DISTANCE CHECK. Everything above this line, and every other mechanical check in
    # the chain, is a defect-ABSENCE detector. A bland page has no defects, so it passes
    # all of them: measured 2026-09-15, a deliberately bland control page cleared
    # design-standard-check.py, the dogfood_gate tripwire AND the impeccable browser
    # detector in one run whose own control fired (RCA
    # rca-design-chain-passes-bland-2026-09-15.md). Seven rounds drifted the same way while
    # every gate stayed green and the founder's word for the result was "bland".
    #
    # design-gap-check.py is the missing instrument: not "is anything wrong" but "how far
    # is this from the exemplars the founder actually named", with floors derived from
    # their captures rather than chosen. This is the half that makes its verdict block.
    if craft.get("require_gap_check"):
        gp = rd / "checks" / GAP_CHECK
        if not gp.is_file():
            probs.append(
                f"missing {gp}: run design-gap-check.py <round> --url-base <served> --write. "
                f"Every other check here can only find defects, and a page with nothing on "
                f"it has none.")
        else:
            try:
                gap = json.loads(gp.read_text())
            except ValueError as e:
                gap, probs = {}, probs + [f"{GAP_CHECK} is not valid JSON: {e}"]
            ent = (gap.get("pages") or {}).get(page.name)
            if not ent:
                probs.append(f"{GAP_CHECK} has no entry for {page.name}")
            elif ent.get("sha256") != sha(page):
                probs.append(f"{GAP_CHECK} is stale for {page.name}: the page changed after "
                             f"it was measured. Re-run design-gap-check.py.")
            else:
                for axis in ent.get("below_floor") or []:
                    probs.append(f"{page.name} is below the exemplar floor. {axis}")
    if craft.get("require_fresh_brief"):
        probs += copied_brief_problems(rd)
    if craft.get("require_dispositions"):
        probs += disposition_problems(rd)
    if craft.get("require_impeccable"):
        ip = rd / "checks" / IMPECCABLE_CHECK
        if not ip.is_file() or not ip.read_text().strip():
            probs.append(
                f"missing or empty {ip}: run the impeccable detector on the SERVED URL "
                f"(URL mode drives a real browser and resolves computed styles, which is "
                f"the only thing it does that the static tripwire cannot) and include a "
                f"known-slop control, or the zeros mean nothing.")
    return probs


def sealed_and_unedited(page: Path) -> bool:
    """True when this exact page bytes already carry a seal receipt.

    `seal` runs the ENTIRE chain before it writes a receipt, so a fresh receipt is
    the evidence that the chain ran, under the ruleset in force at that moment.
    """
    rc = round_dir_for(page) / "receipts.json"
    if not rc.is_file():
        return False
    try:
        rec = json.loads(rc.read_text())
    except ValueError:
        return False
    ent = rec.get(page.name)
    return isinstance(ent, dict) and ent.get("sha256") == sha(page)


NOT_A_ROUND = ".not-a-round"
CORRECTIONS = "corrections.jsonl"
SOURCES = "sources.json"
SOURCE_SUFFIXES = {".astro", ".js", ".mjs", ".ts", ".json", ".md", ".py", ".sh", ".html", ".htm"}


def declared_sources(rd: Path, root: Path) -> dict[Path, str]:
    """{resolved source page -> the round's reason for rendering it} from <round>/sources.json.

    A round whose pages are BUILT from live copy-source files edits those files. On
    askconsulting.io the served pages are built by the newest sealed round, which reads
    `site/<page>/index.html` at build time and carries its markup into the article
    (site/DEPLOY.md, 2026-09-16). So a founder-approved structural edit to a copy source
    IS a design change, the gate is right to say so, and the chain that covers it already
    ran -- in the round that rendered, measured, critiqued and sealed the result.

    What the gate could not see was the link between the two. Without it the only paths
    left were a false wording-correction or a `.not-a-round` marker on a directory whose
    markup does reach a visitor, and both are ways of routing around a gate that is
    correct. Found 2026-09-17 cutting two repeating sections from About in round
    2026-09-17c.
    """
    sp = rd / SOURCES
    if not sp.is_file():
        return {}
    try:
        declared = json.loads(sp.read_text())
    except ValueError:
        return {}
    out: dict[Path, str] = {}
    for rel, why in (declared.get("sources") or {}).items():
        out[(root / str(rel)).resolve()] = str(why or "").strip()
    return out


def _round_dirs(root: Path, cfg: dict) -> list[Path]:
    """Every round directory of this instance: the siblings of the exemplars folder."""
    rounds = Path(cfg.get("rounds_dir") or
                  str(Path(cfg.get("exemplars_dir", "site/design/exemplars")).parent))
    d = (root / rounds).resolve()
    return [p for p in sorted(d.iterdir()) if p.is_dir()] if d.is_dir() else []


def names_the_source(rd: Path, rel: str) -> bool:
    """The round's own files name the source path. A round may not claim a live page it
    does not render: without this, sources.json would be a list anyone could lengthen.

    A build names the page the way it reaches it, so the tails of the path count too
    ("about/index.html" is how the Astro round addresses site/about/index.html). Two
    components minimum: "index.html" alone would match every round ever built.
    """
    parts = Path(rel).parts
    wanted = ["/".join(parts[i:]) for i in range(len(parts) - 1)] or [rel]
    for p in rd.rglob("*"):
        if not p.is_file() or p.name == SOURCES or p.suffix.lower() not in SOURCE_SUFFIXES:
            continue
        try:
            text = p.read_text(errors="ignore")
        except OSError:
            continue
        if any(w in text for w in wanted):
            return True
    return False


def sourced_page(page: Path) -> bool:
    """True when a SEALED round declares this page as a source it renders, at these bytes.

    Self-invalidating by construction: the receipt stores the sha it sealed, so the next
    edit to the source is red again and needs a round of its own. The reason and the
    name-check are re-run here, not only at seal time, so a hand-written receipt cannot
    carry a page past the gate.

    HONEST BOUNDARY: this says the round sealed a build made from these bytes. It does
    not say a human compared the two, and it cannot see a source the round reads but
    never declared.
    """
    cfg, cfg_path = load_config(page)
    if not cfg_path:
        return False
    root = cfg_path.parent
    try:
        rel = str(page.resolve().relative_to(root))
    except ValueError:
        return False
    for rd in _round_dirs(root, cfg):
        why = declared_sources(rd, root).get(page.resolve())
        if not why:
            continue
        rc = rd / "receipts.json"
        if not rc.is_file():
            continue
        try:
            rec = json.loads(rc.read_text())
        except ValueError:
            continue
        if (rec.get("__sources__") or {}).get(rel) != sha(page):
            continue
        if names_the_source(rd, rel):
            return True
    return False


def source_problems(rd: Path, root: Path) -> list[str]:
    """Everything wrong with a round's declared sources, checked before it seals."""
    probs = []
    for src, why in declared_sources(rd, root).items():
        try:
            rel = str(src.relative_to(root))
        except ValueError:
            probs.append(f"{SOURCES} lists {src}, which is outside {root}")
            continue
        if not src.is_file():
            probs.append(f"{SOURCES} lists {rel}, which does not exist")
        elif not why:
            probs.append(f"{SOURCES} gives no reason for {rel}. A round says in writing why "
                         f"it renders a live page before it seals that page's words.")
        elif not names_the_source(rd, rel):
            probs.append(f"{SOURCES} lists {rel}, which nothing in this round names. A round "
                         f"cannot seal a page it does not render.")
    return probs


# Words a search engine or a link preview shows are wording too. Found 2026-09-16 auditing
# askconsulting.io: the false "39 cases, 288 evidence items" and "two blocklists" also sat in
# meta content and JSON-LD, which the correction path counted as design and so could not fix.
WORDING_META = {"description", "og:description", "og:title", "og:image:alt",
                "twitter:description", "twitter:title", "twitter:image:alt"}
WORDING_JSONLD_KEYS = {"text", "description", "name", "headline", "alternateName"}
# An Offer's price is a published claim, not structure. Founder, 2026-09-16: "remove the $1,000
# from anywhere in the site"; the structured-data copy could not be removed as a correction while
# its price keys counted as design. Only inside an Offer: a price key anywhere else stays design.
OFFER_CLAIM_KEYS = {"price", "priceCurrency"}
WORDING = "<wording>"


def _jsonld_shape(value, key=None):
    """JSON-LD with its prose values blanked: keys, types, URLs and every other value stay."""
    if isinstance(value, dict):
        offer = value.get("@type") == "Offer"
        return {k: _jsonld_shape(v, k) for k, v in value.items()
                if not (offer and k in OFFER_CLAIM_KEYS)}
    if isinstance(value, list):
        return [_jsonld_shape(v, key) for v in value]
    if isinstance(value, str) and key in WORDING_JSONLD_KEYS:
        return WORDING
    return value


class _Shape(HTMLParser):
    """Everything about a page except its words: tags, attributes, and the contents of script
    and style (a CSS or JS change is a design change, even though it arrives as text). Words are
    the visible text, image alt text, the preview meta content (WORDING_META) and the prose
    values inside JSON-LD (WORDING_JSONLD_KEYS)."""

    RAW = {"script", "style"}

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.out, self._raw, self._jsonld = [], 0, False

    def _attrs(self, tag, attrs):
        d = {k: v or "" for k, v in attrs}
        if tag == "meta" and (d.get("name") in WORDING_META or d.get("property") in WORDING_META):
            d["content"] = WORDING
        if tag == "img" and "alt" in d:
            d["alt"] = WORDING
        return tuple(sorted(d.items()))

    def handle_starttag(self, tag, attrs):
        self.out.append(("start", tag, self._attrs(tag, attrs)))
        if tag in self.RAW:
            self._raw += 1
            self._jsonld = tag == "script" and dict(attrs).get("type") == "application/ld+json"

    def handle_startendtag(self, tag, attrs):
        self.out.append(("empty", tag, self._attrs(tag, attrs)))

    def handle_endtag(self, tag):
        self.out.append(("end", tag))
        if tag in self.RAW and self._raw:
            self._raw -= 1
            self._jsonld = False

    def handle_data(self, data):
        if not self._raw:
            return
        if self._jsonld:
            try:
                self.out.append(("jsonld", json.dumps(_jsonld_shape(json.loads(data)), sort_keys=True)))
                return
            except ValueError:
                pass  # unparseable JSON-LD is compared as raw text, like any script
        self.out.append(("raw", data))


def page_shape(text: str) -> list:
    sh = _Shape()
    sh.feed(text)
    sh.close()
    return sh.out


def _git(page: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(["git", "-C", str(page.parent), *args], capture_output=True, text=True)


def _committed_text(page: Path, commit: str) -> str | None:
    top = _git(page, "rev-parse", "--show-toplevel")
    if top.returncode:
        return None
    rel = page.resolve().relative_to(Path(top.stdout.strip()).resolve())
    shown = _git(page, "show", f"{commit}:{rel.as_posix()}")
    return shown.stdout if shown.returncode == 0 else None


def corrected_page(page: Path) -> bool:
    """True when this exact page carries a logged correction whose only change, against the
    committed version it corrects, is wording.

    Founder, 2026-09-16, choosing the fix after this gate blocked a one-sentence correction of a
    false claim on a live work page: "Add a corrections path". A correction is not a design
    round: the page was already public, and holding a fix to a false claim behind a brief, three
    directions and a reader gate leaves the false claim standing. The shape check runs again
    here, not only when the entry is written, so a hand-written log line cannot carry a
    structural change past the gate."""
    log = page.parent / CORRECTIONS
    if not log.is_file():
        return False
    cur = sha(page)
    for line in log.read_text().splitlines():
        try:
            ent = json.loads(line)
        except ValueError:
            continue
        if ent.get("page") != page.name or ent.get("after_sha256") != cur:
            continue
        if not str(ent.get("reason", "")).strip():
            continue
        before = _committed_text(page, str(ent.get("before_commit", "")))
        if before is not None and page_shape(before) == page_shape(page.read_text()):
            return True
    return False


def correct(page: Path, reason: str) -> int:
    """Log a wording-only correction to an already-committed page."""
    if not reason.strip():
        print("correct: a reason is required; the log says why the page changed", file=sys.stderr)
        return 2
    if not page.is_file():
        print(f"correct: page not found: {page}", file=sys.stderr)
        return 2
    rel_status = _git(page, "status", "--porcelain", "--", page.name)
    if rel_status.returncode:
        print(f"correct: {page} is not in a git repository, so there is no public version to compare", file=sys.stderr)
        return 2
    if rel_status.stdout.strip():
        before_commit = _git(page, "rev-parse", "HEAD").stdout.strip()
    else:
        last = _git(page, "log", "-n", "1", "--format=%H", "--", page.name).stdout.strip()
        before_commit = (last + "^") if last else ""
        if before_commit:
            before_commit = _git(page, "rev-parse", before_commit).stdout.strip()
    before = _committed_text(page, before_commit) if before_commit else None
    if before is None:
        print(f"correct: {page.name} has no committed earlier version, so it is new, not a correction", file=sys.stderr)
        return 2
    if page_shape(before) != page_shape(page.read_text()):
        print(f"correct: {page.name} is not a wording change: its tags, attributes, CSS or scripts "
              f"differ from {before_commit[:12]}. That is a design change and needs the chain.", file=sys.stderr)
        return 2
    entry = {"page": page.name, "before_commit": before_commit,
             "before_sha256": hashlib.sha256(before.encode()).hexdigest(),
             "after_sha256": sha(page), "reason": reason.strip(),
             "at": time.strftime("%Y-%m-%dT%H:%M:%S")}
    with (page.parent / CORRECTIONS).open("a") as fh:
        fh.write(json.dumps(entry) + "\n")
    print(f"correct: logged a wording correction to {page.name} against {before_commit[:12]}")
    return 0


def tool_directory_problems(page: Path) -> list[str] | None:
    """None when this page is an ordinary round page. A list (possibly empty) when its
    directory has declared itself NOT a design round.

    Why this exists, twice in one session on 2026-09-15: a known-slop control page written
    to prove the tripwire was alive, and a type specimen comparing free faces, were both
    treated as rounds of one with no brief. Neither is a page a visitor reaches and neither
    can ever have a brief, three directions or a reader gate. A gate that blocks on work it
    structurally cannot accept is the pressure that makes someone route around it, which is
    the opposite of what it is for.

    It is narrow on purpose:
      - the marker carries a REASON, and an empty one is refused, so the directory says
        what it is rather than just opting out
      - a directory holding brief.md IS a round and the marker cannot switch it off, so
        this can never turn the chain off for real work
    """
    d = page.parent
    marker = d / NOT_A_ROUND
    if not marker.is_file():
        return None
    if (d / "brief.md").is_file():
        return [f"{marker} sits in a directory that holds brief.md, which makes it a design "
                f"round. A round cannot declare itself not a round. Remove one or the other."]
    try:
        reason = marker.read_text().strip()
    except OSError:
        reason = ""
    if not reason:
        return [f"{marker} carries no reason. A directory may declare that it holds tools "
                f"rather than round pages, and it says in writing what they are."]
    return []


def withdrawn_reason(rd: Path) -> str | None:
    """The round's own one-way declaration that it will never be shown, or None.

    craft_problems() already honours this and returns early. Everything OUTSIDE that
    function did not, so a withdrawn round was still held to standard.json entries and to
    the seal. Found 2026-09-15 withdrawing round g: the gate demanded a seal on a round
    whose whole point was that it must not be sealed.

    That is the same shape the withdrawal hatch exists to prevent, in its own docstring:
    holding a withdrawn round to the bar "only forces its author to either fake a receipt
    or stay stuck". It has to short-circuit the WHOLE chain, not one function of it.

    Still one-way and still costly: the reason is mandatory, and nothing here lets a round
    be withdrawn and then presented, because presenting it means writing it back to a live
    status in the open.
    """
    mp = rd / CRAFT_MANIFEST
    if not mp.is_file():
        return None
    try:
        declared = json.loads(mp.read_text())
    except ValueError:
        return None
    if declared.get("status") != "withdrawn":
        return None
    return str(declared.get("reason", "")).strip() or ""


def implemented_direction(rd: Path, cfg_path: Path | None) -> tuple[dict | None, list[str]]:
    """The decision a round BUILDS, from craft-manifest.json `implements`, or None.

    The chain is built for fanning out: three directions, nine questions each, then the founder
    picks. It had no shape for the round that comes after the pick, and a round that builds one
    picked direction was held to three headings and 27 answers. The only ways to comply were to
    invent two directions nobody is offering, or to copy 18 answers forward to satisfy a counter.
    Both are the cheapest-passing-artifact failure the craft tier exists to stop, so the gate
    grew the missing shape instead. Found 2026-09-17 building the founder's pick from round
    2026-09-17d ("Drawing 1 + D1").

    It cannot be used to skip the fan-out, which is the whole point of the three:

      - it must NAME a round that exists, in this instance's own rounds directory
      - that round must be SEALED (it has receipts), so it was measured, not merely started
      - that round must itself carry three direction headings
      - the reason is mandatory and is where the founder's own words go

    Shape, in the round's craft-manifest.json:

        "implements": {"round": "2026-09-17d", "direction": "D1", "reason": "founder, verbatim"}
    """
    mp = rd / CRAFT_MANIFEST
    if not mp.is_file():
        return None, []
    try:
        declared = json.loads(mp.read_text())
    except ValueError:
        return None, []
    impl = declared.get("implements")
    if not isinstance(impl, dict):
        return None, []
    named, direction = str(impl.get("round", "")).strip(), str(impl.get("direction", "")).strip()
    reason = str(impl.get("reason", "")).strip()
    if not named or not direction:
        return None, [f"{CRAFT_MANIFEST} `implements` needs both a round and a direction; it is the "
                      f"record of which fan-out this round builds."]
    if not reason:
        return None, [f"{CRAFT_MANIFEST} `implements` carries no reason. A round that builds a pick "
                      f"says in writing why that one won, in the words it was picked in."]
    src = rd.parent / named
    if not src.is_dir():
        return None, [f"{CRAFT_MANIFEST} `implements` names round '{named}', which does not exist "
                      f"in {rd.parent}."]
    if not (src / "receipts.json").is_file():
        return None, [f"{CRAFT_MANIFEST} `implements` names round '{named}', which is not sealed. A "
                      f"pick can only be made from a round that was measured."]
    src_dirs = (src / "directions.md").read_text() if (src / "directions.md").is_file() else ""
    n_src = len(re.findall(r"^#{1,3}\s+\S", src_dirs, re.M))
    if n_src < 3:
        return None, [f"{CRAFT_MANIFEST} `implements` names round '{named}', which carries {n_src} "
                      f"direction heading(s). The three are what a pick is picked from."]
    return impl, []


# ---------------------------------------------------------------------------------------
# THE VISION STAGE (2026-09-18, founder-directed).
#
# Founder: "add this process into the design chain tool we built so it is forced into the
# process." The process he means: sit down and say the VISION first, keep a running notebook
# of the key points and reasons, break it into components, spec each one, review the specs,
# then build.
#
# WHY IT IS A GATE AND NOT ADVICE. On 2026-09-17/18 this chain produced three fully specced,
# measured, critiqued and SEALED directions that were all wrong, and the persona gate found
# 51 negatives against 1 "it helped" across 23 runs. Nothing in the chain was skipped. Every
# brief was assembled from CONSTRAINTS (word budgets, type sizes, banned patterns, pain
# anchors) and not one of them said what the page was trying to BE. A chain that checks the
# shape of the work cannot notice that the work is aimed at nothing.
#
# WHAT THIS CAN AND CANNOT SEE, stated here so its silence is not over-read:
#   IT CAN see that a vision file exists, that it carries at least N blocks marked as the
#   founder's own words, that the round's brief quotes one of them verbatim, and that a page
#   whose round declares a component has a spec for that component carrying a review marker.
#   IT CANNOT see whether the vision is any good, whether the quoted words are really his, or
#   whether a spec marked reviewed was actually read. A marker makes skipping DELIBERATE. It
#   does not make it impossible, and no regex will.
# ---------------------------------------------------------------------------------------

VISION_DEFAULTS = {
    "file": "design/VISION.md",
    "specs_dir": "design/specs",
    "min_founder_quotes": 3,
    "require_brief_quotes_vision": True,
    "review_marker": r"(?im)^\s*REVIEWED BY FOUNDER:\s*\S+",
}
# A founder block is a dated line naming him and carrying his words in quotes. The same shape
# decisions.md has used since 2026-09-15, so the notebook and the canon read alike.
FOUNDER_QUOTE_RE = re.compile(r"(?im)^\s*[*_>\s-]*Founder[^\n:]*:\s*.*?[\"\u201c\u2018']")


def vision_cfg(cfg: dict) -> dict:
    out = dict(VISION_DEFAULTS)
    out.update((cfg or {}).get("vision") or {})
    return out


def vision_problems(rd: Path, cfg: dict, cfg_path: Path | None) -> list[str]:
    """The vision stage, checked. Returns [] when the config declares no vision block AND no
    vision file exists, so an instance that has not adopted this is not broken by it; but an
    instance that HAS a vision file is held to the whole stage. Non-adoption is visible in the
    config rather than silent."""
    if cfg_path is None:
        return []
    vc = vision_cfg(cfg)
    vf = (cfg_path.parent / vc["file"])
    declared = bool((cfg or {}).get("vision"))
    if not declared and not vf.is_file():
        return []                                   # not adopted here; say nothing
    probs: list[str] = []
    if not vf.is_file():
        return [f"missing {vf}: the chain declares a vision stage and the vision has not been "
                f"written. The brief is assembled from constraints; the vision is what the page "
                f"is FOR, and a round briefed without one is aimed at nothing."]
    vtext = vf.read_text()
    quotes = FOUNDER_QUOTE_RE.findall(vtext)
    need = int(vc["min_founder_quotes"])
    if len(quotes) < need:
        probs.append(f"{vf} carries {len(quotes)} founder block(s); {need} required. The vision is "
                     f"HIS, in his words. A vision written by the builder is the builder grading "
                     f"his own aim.")
    if vc.get("require_brief_quotes_vision"):
        brief = (rd / "brief.md")
        btxt = _norm(brief.read_text()) if brief.is_file() else ""
        lines = [ln.strip() for ln in vtext.splitlines()
                 if len(ln.strip()) > 40 and FOUNDER_QUOTE_RE.match(ln)]
        if lines and not any(_norm(ln) in btxt for ln in lines):
            probs.append(f"brief.md quotes no line from {vf.name} verbatim. The round has to be "
                         f"built FROM the vision, not merely near it.")
    # component specs: only checked when the round declares which component it builds
    man = {}
    mpath = rd / CRAFT_MANIFEST
    if mpath.is_file():
        try:
            man = json.loads(mpath.read_text())
        except json.JSONDecodeError:
            man = {}          # craft_problems already reports a malformed manifest; do not double-report
    comp = man.get("component")
    if comp:
        sp = cfg_path.parent / vc["specs_dir"] / f"{comp}.md"
        if not sp.is_file():
            probs.append(f"{CRAFT_MANIFEST} declares component '{comp}' and {sp} does not exist. "
                         f"Specs come before the build, which is the whole point of the stage.")
        elif not re.search(vc["review_marker"], sp.read_text()):
            probs.append(f"{sp} carries no 'REVIEWED BY FOUNDER: <date>' line. A spec the founder "
                         f"has not tightened is the builder's spec.")
    return probs


def chain_problems(page: Path, honor_seal: bool = True) -> list[str]:
    """Everything missing or stale for one page. Empty list = chain complete.

    honor_seal=True (the passive gate): an already-sealed, unedited page is HISTORY
    and is not re-litigated. Tightening the ruleset applies to rounds that seal from
    now on, never backwards.

    Scar, 2026-09-15: adding a fifth owner (the pain model) and require_fresh_brief
    turned this gate red on ALL FIVE rounds that had already sealed, blocking the end
    of the turn with findings no edit could clear -- you cannot retroactively make a
    past round have read a file. A gate red on its own population gets switched off,
    and a switched-off gate protects nothing. Same call plan-lint made with its dated
    grandfather and linear-filer-label-lint made after measuring 8 filers and 1
    compliant.

    honor_seal=False (an explicit `seal`): today's full bar, no grandfather. Re-sealing
    a round is a claim about it NOW, so it is checked against the rules now. That is
    what keeps this from being a blanket amnesty: the escape hatch is one-way and only
    the passive path takes it.
    """
    probs: list[str] = []
    if not page.is_file():
        return [f"page not found: {page}"]
    declared = tool_directory_problems(page)
    if declared is not None:
        return declared
    if corrected_page(page):
        return []
    if sourced_page(page):
        return []
    reason = withdrawn_reason(round_dir_for(page))
    if reason is not None:
        return [] if reason else [
            f"{CRAFT_MANIFEST} declares status 'withdrawn' with no reason. A round may be "
            f"withdrawn, but the record says why."]
    if honor_seal and sealed_and_unedited(page):
        return []
    rd = round_dir_for(page)
    cfg, cfg_path = load_config(page)
    if not cfg:
        probs.append(f"no {CONFIG_NAME} found above {page} (the instance has no owner anchors configured)")

    for name in CHAIN_FILES:
        if not (rd / name).is_file():
            probs.append(f"missing {rd / name}")
    for name in CHAIN_DIRS:
        d = rd / name
        if not d.is_dir() or not any(d.iterdir()):
            probs.append(f"missing or empty {d}/")

    # brief: verbatim anchors, read live
    brief = (rd / "brief.md").read_text() if (rd / "brief.md").is_file() else ""
    nb = _norm(brief)
    for label, line in anchors_from_owners(cfg, cfg_path):
        if line in ("__MISSING_OWNER_FILE__", "__NO_MATCH__"):
            probs.append(f"owner anchor unreadable: {label} -> {line}")
        elif _norm(line) not in nb:
            probs.append(f"brief.md does not quote verbatim: {label}")

    probs += vision_problems(rd, cfg, cfg_path)

    # directions: three, plus an exemplar citation when exemplars exist
    dirs_txt = (rd / "directions.md").read_text() if (rd / "directions.md").is_file() else ""
    n_dir = len(re.findall(r"^#{1,3}\s+\S", dirs_txt, re.M))
    impl, impl_probs = implemented_direction(rd, cfg_path)
    probs += impl_probs
    need_dirs = 1 if impl else 3
    if n_dir < need_dirs:
        probs.append(f"directions.md names {n_dir} direction heading(s); "
                     f"{'one is' if need_dirs == 1 else 'three are'} required")
    ex_dir = (cfg_path.parent / cfg.get("exemplars_dir", "design/exemplars")) if cfg_path else None
    if ex_dir and ex_dir.is_dir():
        ex = [p.name for p in ex_dir.iterdir() if p.is_file()]
        if ex and not any(name in dirs_txt for name in ex):
            probs.append(f"directions.md cites none of the exemplars in {ex_dir}: {ex}")

    # critique: nine questions per direction (count of numbered answers)
    crit = (rd / "critique.md").read_text() if (rd / "critique.md").is_file() else ""
    n_q = len(re.findall(r"^\s*(?:\d\.|\*\*\d\.|Q\d)", crit, re.M))
    # An implementing round answers the nine for the one direction it builds. The other two were
    # answered in the round it names, which this gate has already checked and sealed.
    n_crit = 1 if impl else max(n_dir, 1)
    if n_q < NINE_QUESTIONS * n_crit:
        probs.append(f"critique.md has {n_q} numbered answers; {NINE_QUESTIONS} per direction x {n_crit} = {NINE_QUESTIONS*n_crit} required")

    # standard: pass true and hash matches THIS page
    std_path = rd / "standard.json"
    if std_path.is_file():
        try:
            std = json.loads(std_path.read_text())
        except ValueError:
            std = {}
        entries = std if isinstance(std, list) else [std]
        mine = [e for e in entries if isinstance(e, dict) and e.get("page") == page.name]
        cur = sha(page)
        if not mine:
            probs.append(f"standard.json has no entry for {page.name}")
        elif not any(e.get("pass") is True and e.get("sha256") == cur for e in mine):
            probs.append(f"standard.json for {page.name}: pass is not true or hash is stale (re-run design-standard-check.py)")

    probs += craft_problems(rd, page, cfg, cfg_path)

    # receipts: sealed, and fresh
    rc = rd / "receipts.json"
    if not rc.is_file():
        probs.append(f"not sealed: run `design-chain-gate.py seal {rd}`")
    else:
        try:
            rec = json.loads(rc.read_text())
        except ValueError:
            rec = {}
        ent = rec.get(page.name)
        if not ent:
            probs.append(f"receipts.json has no entry for {page.name}")
        elif ent.get("sha256") != sha(page):
            probs.append(f"receipt stale for {page.name}: page edited after seal; redo the chain and seal again")
    return probs


def seal(rd: Path) -> int:
    pages = [p for p in rd.iterdir() if p.is_file() and is_page(str(p))]
    if not pages:
        print(f"seal: no page files in {rd}", file=sys.stderr)
        return 2
    rc = rd / "receipts.json"
    bad = []
    seal_cfg, _ = load_config(pages[0])
    # A withdrawn round is never going to be shown, so it has nothing to seal and gets NO
    # receipt. The first version of dc-02 skipped the producers for it and then fell through
    # and wrote one anyway: withdraw, seal, delete the manifest, and the page read COMPLETE
    # on a receipt nothing had measured (adversarial review of c598d5f5, reproduced).
    why_withdrawn = withdrawn_reason(rd)
    if why_withdrawn == "":
        # withdrawing is allowed; withdrawing without saying why is not (unchanged rule)
        print(f"seal REFUSED:\n  {CRAFT_MANIFEST}: declares status 'withdrawn' with no reason. A "
              f"round may be withdrawn, but the record says why.", file=sys.stderr)
        return 2
    if why_withdrawn is not None:
        print(f"seal: {rd.name} is withdrawn. Nothing to seal, no receipt written.")
        return 0
    measured = producer_problems(rd, pages, seal_cfg)
    bad += measured
    reported = {name for name, _ in measured}
    for p in pages:
        if rc.is_file():
            # ignore the existing receipt so a re-seal re-validates everything else
            probs = [x for x in chain_problems(p, honor_seal=False) if "receipt" not in x and "not sealed" not in x]
        else:
            probs = [x for x in chain_problems(p, honor_seal=False) if "not sealed" not in x]
        if p.name in reported:
            probs = [x for x in probs if not x.startswith("standard.json for")]
        if probs:
            bad.append((p.name, probs))
    cfg, cfg_path = load_config(pages[0])
    root = cfg_path.parent if cfg_path else rd
    sprobs = source_problems(rd, root)
    if sprobs:
        bad.append((SOURCES, sprobs))
    if bad:
        print("seal REFUSED:", file=sys.stderr)
        for name, probs in bad:
            for x in probs:
                print(f"  {name}: {x}", file=sys.stderr)
        return 2
    rec = {p.name: {"sha256": sha(p), "sealed": time.strftime("%Y-%m-%dT%H:%M:%S")} for p in pages}
    srcs = declared_sources(rd, root)
    if srcs:
        rec["__sources__"] = {str(s.relative_to(root)): sha(s) for s in srcs}
    rc.write_text(json.dumps(rec, indent=2) + "\n")
    print(f"sealed {len(pages)} page(s) in {rd}")
    return 0


# ---------------------------------------------------------------- session ledger

def ledger_path(session_id: str) -> Path:
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    return STATE_DIR / f"{re.sub(r'[^A-Za-z0-9_-]', '_', session_id or 'nosession')}.json"


def load_ledger(session_id: str) -> dict:
    p = ledger_path(session_id)
    try:
        return json.loads(p.read_text())
    except (OSError, ValueError):
        return {"pages": {}, "bash_marker": 0}


def save_ledger(session_id: str, led: dict) -> None:
    ledger_path(session_id).write_text(json.dumps(led, indent=2))


def scan_roots(payload: dict) -> list[Path]:
    roots = []
    for cand in (payload.get("cwd"), os.environ.get("CLAUDE_PROJECT_DIR"), os.environ.get("DESIGN_CHAIN_EXTRA_ROOT")):
        if cand:
            roots.append(Path(cand))
    reg = Path(os.environ.get("CLAUDE_PROJECT_DIR", "")) / "instance-registry.json"
    if reg.is_file():
        try:
            for inst in json.loads(reg.read_text()).get("instances", []):
                if inst.get("path"):
                    roots.append(Path(inst["path"]))
        except ValueError:
            pass
    # de-dup by prefix
    out: list[Path] = []
    for r in sorted({r.resolve() for r in roots if r.exists()}, key=lambda p: len(str(p))):
        if not any(str(r).startswith(str(o) + os.sep) or r == o for o in out):
            out.append(r)
    return out


PRUNE = {"node_modules", ".git", "dist", "build", ".next", "coverage", "site-packages", ".venv", "venv", "__pycache__"}


def newer_pages(roots: list[Path], since: float) -> list[str]:
    found = []
    for root in roots:
        for dirpath, dirnames, filenames in os.walk(root):
            dirnames[:] = [d for d in dirnames if d not in PRUNE]
            for fn in filenames:
                if Path(fn).suffix.lower() in PAGE_EXTS:
                    fp = os.path.join(dirpath, fn)
                    try:
                        if os.path.getmtime(fp) >= since and is_page(fp):
                            found.append(fp)
                    except OSError:
                        pass
    return found


def open_pages(led: dict) -> list[tuple[str, list[str]]]:
    out = []
    for p in list(led.get("pages", {})):
        if not Path(p).exists():
            continue
        probs = chain_problems(Path(p))
        if probs:
            out.append((p, probs))
    return out


def block(msg_lines: list[str]) -> int:
    print("DESIGN CHAIN GATE (blocked): a page was made this session and its design chain is not complete.", file=sys.stderr)
    for ln in msg_lines[:40]:
        print("  " + ln, file=sys.stderr)
    print("  Steps: brief.md (verbatim owner anchors) -> directions.md (3) -> design-standard-check.py -> critique.md (9 per direction) -> proof.md -> checks/ -> gate/ -> `design-chain-gate.py seal <round>`.", file=sys.stderr)
    print("  Override is DESIGN_CHAIN_ALLOW=1 in the founder's shell only.", file=sys.stderr)
    return 2


# ---------------------------------------------------------------- hook dispatch

def hook(payload: dict) -> int:
    if os.environ.get("DESIGN_CHAIN_ALLOW") == "1":
        return 0
    ev = payload.get("hook_event_name", "")
    tool = payload.get("tool_name", "")
    ti = payload.get("tool_input") or {}
    sid = payload.get("session_id", "")
    led = load_ledger(sid)

    if ev == "PostToolUse" and tool in ("Write", "Edit", "MultiEdit"):
        fp = ti.get("file_path", "")
        if is_page(fp):
            led["pages"][str(Path(fp).resolve())] = {"first_seen": time.time(), "via": tool}
            save_ledger(sid, led)
        return 0

    if ev == "PreToolUse" and tool == "Bash":
        led["bash_marker"] = time.time() - 1
        save_ledger(sid, led)
        cmd = ti.get("command", "") or ""
        opens = open_pages(led)
        # naming an open page is only a block when the command SHOWS it; the chain's own
        # steps name the page on purpose (design-standard-check.py <page>.html)
        if opens and BASH_SHOW_RE.search(cmd):
            return block([f"{p}: {x}" for p, probs in opens for x in probs[:3]])
        return 0

    if ev == "PostToolUse" and tool == "Bash":
        since = float(led.get("bash_marker") or (time.time() - 60))
        for fp in newer_pages(scan_roots(payload), since):
            led["pages"].setdefault(str(Path(fp).resolve()), {"first_seen": time.time(), "via": "Bash"})
        save_ledger(sid, led)
        return 0

    if ev == "PreToolUse" and (tool in PUBLISH_TOOLS or tool.startswith(SHOW_TOOLS_PREFIX)):
        opens = open_pages(led)
        # publish surfaces also check what they carry, ledger or not
        if tool in PUBLISH_TOOLS:
            carried = []
            raw = ti.get("files") or ti.get("file_path") or []
            for f in (raw if isinstance(raw, list) else [raw]):
                f = f if isinstance(f, str) else (f.get("path") if isinstance(f, dict) else "")
                if not f:
                    continue
                fpath = Path(f)
                if is_page(f):
                    carried.append(fpath)
                elif fpath.suffix.lower() in (".png", ".jpg", ".jpeg", ".webp", ".pdf"):
                    for sib in fpath.parent.glob("*"):
                        if is_page(str(sib)):
                            carried.append(sib)
            for c in carried:
                probs = chain_problems(c)
                if probs:
                    opens.append((str(c), probs))
        if opens:
            return block([f"{p}: {x}" for p, probs in opens for x in probs[:3]])
        return 0

    if ev == "Stop":
        if payload.get("stop_hook_active"):
            return 0
        opens = open_pages(led)
        if opens:
            return block([f"{p}: {x}" for p, probs in opens for x in probs[:4]])
        return 0
    return 0


def main(argv: list[str]) -> int:
    if argv and argv[0] == "correct":
        reason = argv[argv.index("--reason") + 1] if "--reason" in argv else ""
        return correct(Path(argv[1]).resolve(), reason)
    if argv and argv[0] == "status-page":
        probs = chain_problems(Path(argv[1]).resolve())
        print("COMPLETE" if not probs else "OPEN")
        for x in probs:
            print("   - " + x)
        return 2 if probs else 0
    if argv and argv[0] == "seal":
        return seal(Path(argv[1]).resolve())
    if argv and argv[0] == "status":
        rd = Path(argv[1]).resolve()
        pages = [p for p in rd.iterdir() if p.is_file() and is_page(str(p))]
        rc = 0
        for p in pages:
            probs = chain_problems(p)
            print(f"{p.name}: {'COMPLETE' if not probs else 'OPEN'}")
            for x in probs:
                print("   - " + x)
            rc = rc or (2 if probs else 0)
        return rc
    try:
        payload = json.load(sys.stdin)
    except Exception:
        return 0  # unreadable payload: fail open, there is nothing to judge
    return hook(payload)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
