#!/usr/bin/env python3
"""design-chain-gate: web design work cannot be shown, tested, sent or left behind
until the agreed design steps have produced their receipts.

WHY (founder, 2026-09-15, after two rounds of first screens ignored the canon):
  "When I try to create web design, you continuously find ways to go back to your
  generic stuff. If it's not reading the prose, ignoring the prose, or going around it."
  A lint on the page is a blocklist and was rejected. This is the other shape: a
  chain of receipts the harness demands before the next tool call can happen.

THE THREE HOLES THIS CLOSES (each one was used the same day):
  1. Pages generated by a script (build2.py wrote six .html files) never hit the
     Write hook. So the ledger is fed by a filesystem scan after every Bash call,
     not by the Write tool alone.
  2. Pages built outside design-room/ never hit publish_gate. So there is no path
     scope: any page file anywhere (except the internal allowlist) is in scope.
  3. A brief written from memory is how the generic layout comes back. So the brief
     must contain lines extracted LIVE from the owner files, verbatim.

WHAT IT DOES NOT BLOCK (2026-09-15): the chain's own steps. Measuring, serving,
screenshotting and sealing a page are how the chain CLOSES; blocking them made the
command unrunnable. See BASH_SHOW_RE below.

THE CHAIN, per page, in the round directory that holds the page:
  brief.md        verbatim anchors from the owner files + the three-line brief
  directions.md   three directions; cites an exemplar when exemplars/ is non-empty
  standard.json   written by design-standard-check.py: pass true, sha256 of the page
  critique.md     the nine DNA questions answered per direction
  proof.md        each artifact's proof kind and its INDEX record
  checks/         bio_gate + voice-lint outputs
  gate/           ICP-persona comprehension answers
  receipts.json   written by `seal`; sha256 per page; stale on any later edit

HOOK CONTRACT: reads the hook JSON on stdin, keys on hook_event_name and tool_name.
exit 0 = pass, exit 2 = block (stderr goes to the model). `seal` and `status` are CLI
subcommands. Fails OPEN only when the payload itself is unreadable; every ambiguity
about a page in the ledger fails CLOSED.

OVERRIDE: DESIGN_CHAIN_ALLOW=1 in the founder's shell. No in-file marker exists, on
purpose: a marker the agent can write is not an override, it is a hole.

HONEST BOUNDARY: the scan after a Bash call covers the Bash cwd, the project dir, the
scratchpad and the registered instance roots. A page written somewhere else by a
script is not seen until it is sent or opened by a tool this gate watches.

stdlib only. Self-test: test_design_chain_gate.py.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import sys
import time
from pathlib import Path

PAGE_EXTS = {".html", ".htm", ".astro", ".jsx", ".tsx", ".vue", ".svelte"}
# Internal HTML the founder alone sees. A path segment match, not a marker in the file.
INTERNAL_MARKERS = (
    "/node_modules/", "/.git/", "/dist/", "/build/", "/.next/", "/coverage/",
    "daily-schedule", "morning-log", "/logs/", "/log/", "/test", "/tests/", "/fixtures/",
    "/schedule", "/dashboard", "/report", "/vendor/", "/site-packages/", "/.playwright-mcp/",
    "/exemplars/",
)
CHAIN_FILES = ("brief.md", "directions.md", "standard.json", "critique.md", "proof.md")
CHAIN_DIRS = ("checks", "gate")
# The BAR half, switched on per instance by a `craft` block in design-chain.json.
# Everything above this line is a FLOOR: it sees missing files, unquoted anchors, word
# counts and type sizes. A round cleared all of it on 2026-09-15 while shipping three
# wireframes with no imagery, no motion and no depth -- the failure
# q-system/lessons/a-defect-absence-gate-is-a-floor-not-a-finish-line.md already named,
# distilled from cole-gtm rca-design-room-skipped-premium-tools-2026-06-25. Its four
# causes, all of which recurred: a floor-detector became the definition of done;
# grounding enforced provenance, not ambition; the direction was resolved at concept
# level with no execution tier, so premium and floor realizations were equally
# compliant; effort-economy ran downhill to the cheapest passing artifact.
CRAFT_MANIFEST = "craft-manifest.json"
IMPECCABLE_CHECK = "impeccable.txt"
# Bash commands that put a page in front of a HUMAN. Blocked while the chain is open.
#
# WHY this list is short (2026-09-15, found the first time the command was run end to
# end): it used to also carry screenshot|playwright|http.server|shoot*.py|gate*.py|
# comprehension, and the branch below additionally blocked any command merely NAMING an
# open page. Those are the chain's own steps -- design-standard-check.py writes
# standard.json (step 5), the serve it measures against, shoot + gate_icp (step 9) and
# `seal` itself (step 10). The gate blocked every step of the command it enforces, so a
# chain opened by an agent could never be closed by one. Rendering a page to MEASURE it
# is not showing it; the surfaces that reach the founder (SendUserFile, Artifact, the
# browser MCP tools) and the Stop hook are unchanged and still block.
BASH_SHOW_RE = re.compile(r"(open\s+-a\b|vercel\s+deploy|\bopen\s+[^|;&]*\.(?:html?|png|jpe?g|pdf)\b)", re.I)
SHOW_TOOLS_PREFIX = ("mcp__playwright__", "mcp__claude-in-chrome__", "mcp__plugin_chrome-devtools")
PUBLISH_TOOLS = ("SendUserFile", "Artifact")
NINE_QUESTIONS = 9
STATE_DIR = Path(os.environ.get("DESIGN_CHAIN_STATE", os.path.expanduser("~/.config/kipi/design-chain")))
CONFIG_NAME = "design-chain.json"


# ---------------------------------------------------------------- helpers

def _norm(s: str) -> str:
    return re.sub(r"\s+", " ", s).strip().lower()


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def is_page(path: str) -> bool:
    p = str(Path(path).resolve()) if path else ""
    if not p or Path(p).suffix.lower() not in PAGE_EXTS:
        return False
    low = p.lower() + "/"
    return not any(m in low for m in INTERNAL_MARKERS)


def find_config(start: Path) -> Path | None:
    """Nearest design-chain.json walking up from the page, then the project dir."""
    for d in [start] + list(start.parents):
        c = d / CONFIG_NAME
        if c.is_file():
            return c
    proj = os.environ.get("CLAUDE_PROJECT_DIR")
    if proj and (Path(proj) / CONFIG_NAME).is_file():
        return Path(proj) / CONFIG_NAME
    return None


def load_config(page: Path) -> tuple[dict, Path | None]:
    c = find_config(page.parent)
    if not c:
        return {}, None
    try:
        return json.loads(c.read_text()), c
    except (OSError, ValueError):
        return {}, c


def anchors_from_owners(cfg: dict, cfg_path: Path | None) -> list[tuple[str, str]]:
    """(label, verbatim line) for every anchor, read LIVE from the owner files.
    A missing owner file or an anchor that matches nothing is itself a failure the
    caller reports: the brief cannot quote what does not exist."""
    out = []
    root = cfg_path.parent if cfg_path else Path(".")
    for own in cfg.get("owners", []):
        f = root / own["file"]
        try:
            lines = f.read_text().splitlines()
        except OSError:
            out.append((own["file"], "__MISSING_OWNER_FILE__"))
            continue
        for rx in own.get("anchors", []):
            pat = re.compile(rx)
            hit = None
            for ln in lines:
                m = pat.search(ln)
                if m:
                    # a capture group narrows the anchor to the part that must be
                    # quoted (a rule TITLE, not its 900-character paragraph)
                    hit = m.group(1) if m.groups() else ln
                    break
            out.append((f"{own['file']} :: {rx}", hit.strip() if hit else "__NO_MATCH__"))
    return out


def round_dir_for(page: Path) -> Path:
    """The round directory is the nearest ancestor (up to 3 levels) holding brief.md,
    else the page's own directory."""
    for d in [page.parent, page.parent.parent, page.parent.parent.parent]:
        if (d / "brief.md").is_file():
            return d
    return page.parent


# ---------------------------------------------------------------- the chain check

def craft_problems(rd: Path, page: Path, cfg: dict) -> list[str]:
    """The bar-check. Silent unless the instance declares a `craft` block, so an
    instance that has not opted in keeps exactly the behaviour it had.

    It never certifies a page as good, and deliberately has no success message. Green
    here means ONLY "not a wireframe"; the founder's eye and five real buyer
    conversations are the bar (site-design.md section 8). That posture is borrowed
    whole from cole-gtm's check_technique_parity.py, whose docstring carries the
    founder line this all rests on: "when you have a floor, you are programmed to only
    pass the floor."
    """
    craft = cfg.get("craft") or {}
    if not craft:
        return []
    # An undeclared tier is the REQUIRED tier, never the cheap one: silence must not be
    # the easiest way out (the RCA's cause #4, effort-economy toward the cheapest pass).
    if craft.get("tier", "craft") == "wireframe":
        return []

    probs: list[str] = []
    mpath = rd / CRAFT_MANIFEST

    # A ROUND may declare itself a wireframe round, which the instance default must not
    # be flipped to do. Without this the only way to keep an honest copy-test round
    # sealed is to set craft.tier=wireframe in design-chain.json, which silently lowers
    # the bar for every future round -- the opposite of the point. A round-local
    # declaration is narrow, dated by its own directory, and has to carry a reason, so
    # it reads as a labelled exception rather than a quiet downgrade.
    if mpath.is_file():
        try:
            declared = json.loads(mpath.read_text())
        except ValueError:
            declared = {}
        if declared.get("tier") == "wireframe":
            if not str(declared.get("reason", "")).strip():
                return [f"{CRAFT_MANIFEST} declares tier 'wireframe' with no reason. A "
                        f"round may opt out of the craft bar, but it says why, in "
                        f"writing, in the round."]
            return []
    if craft.get("require_craft_manifest"):
        if not mpath.is_file():
            probs.append(
                f"missing {mpath}: at tier '{craft.get('tier', 'craft')}' each direction "
                f"declares its signature moment and the technique that realizes it "
                f"(id, technique, role, reference, import[], applied[]). Without it the "
                f"research is decorative and the cheapest layout wins.")
        else:
            try:
                man = json.loads(mpath.read_text())
            except ValueError as e:
                man, probs = {}, probs + [f"{CRAFT_MANIFEST} is not valid JSON: {e}"]
            techs = man.get("techniques") or []
            if not techs:
                probs.append(f"{CRAFT_MANIFEST} declares no techniques, so nothing was "
                             f"verified. Declaring nothing must not be the cheapest way "
                             f"to comply.")
            else:
                src = page.read_text(errors="replace")
                src = re.sub(r"<!--.*?-->", " ", src, flags=re.DOTALL)
                src = re.sub(r"/\*.*?\*/", " ", src, flags=re.DOTALL)
                for t in techs:
                    if t.get("pages") and page.name not in t["pages"]:
                        continue
                    imp, app = t.get("import") or [], t.get("applied") or []
                    if not imp and not app:
                        probs.append(f"{CRAFT_MANIFEST}: technique "
                                     f"'{t.get('id', '?')}' declares no fingerprint, so it "
                                     f"cannot be verified present")
                        continue
                    missing = [p for p in imp + app if not re.search(p, src)]
                    if missing:
                        probs.append(f"{CRAFT_MANIFEST}: technique '{t.get('id', '?')}' "
                                     f"({t.get('role', '?')}) is declared but absent from "
                                     f"{page.name}: {missing}")
    if craft.get("require_impeccable"):
        ip = rd / "checks" / IMPECCABLE_CHECK
        if not ip.is_file() or not ip.read_text().strip():
            probs.append(
                f"missing or empty {ip}: run the impeccable detector on the SERVED URL "
                f"(URL mode drives a real browser and resolves computed styles, which is "
                f"the only thing it does that the static tripwire cannot) and include a "
                f"known-slop control, or the zeros mean nothing.")
    return probs


def chain_problems(page: Path) -> list[str]:
    """Everything missing or stale for one page. Empty list = chain complete."""
    probs: list[str] = []
    if not page.is_file():
        return [f"page not found: {page}"]
    rd = round_dir_for(page)
    cfg, cfg_path = load_config(page)
    if not cfg:
        probs.append(f"no {CONFIG_NAME} found above {page} (the instance has no owner anchors configured)")

    for name in CHAIN_FILES:
        if not (rd / name).is_file():
            probs.append(f"missing {rd / name}")
    for name in CHAIN_DIRS:
        d = rd / name
        if not d.is_dir() or not any(d.iterdir()):
            probs.append(f"missing or empty {d}/")

    # brief: verbatim anchors, read live
    brief = (rd / "brief.md").read_text() if (rd / "brief.md").is_file() else ""
    nb = _norm(brief)
    for label, line in anchors_from_owners(cfg, cfg_path):
        if line in ("__MISSING_OWNER_FILE__", "__NO_MATCH__"):
            probs.append(f"owner anchor unreadable: {label} -> {line}")
        elif _norm(line) not in nb:
            probs.append(f"brief.md does not quote verbatim: {label}")

    # directions: three, plus an exemplar citation when exemplars exist
    dirs_txt = (rd / "directions.md").read_text() if (rd / "directions.md").is_file() else ""
    n_dir = len(re.findall(r"^#{1,3}\s+\S", dirs_txt, re.M))
    if n_dir < 3:
        probs.append(f"directions.md names {n_dir} direction heading(s); three are required")
    ex_dir = (cfg_path.parent / cfg.get("exemplars_dir", "design/exemplars")) if cfg_path else None
    if ex_dir and ex_dir.is_dir():
        ex = [p.name for p in ex_dir.iterdir() if p.is_file()]
        if ex and not any(name in dirs_txt for name in ex):
            probs.append(f"directions.md cites none of the exemplars in {ex_dir}: {ex}")

    # critique: nine questions per direction (count of numbered answers)
    crit = (rd / "critique.md").read_text() if (rd / "critique.md").is_file() else ""
    n_q = len(re.findall(r"^\s*(?:\d\.|\*\*\d\.|Q\d)", crit, re.M))
    if n_q < NINE_QUESTIONS * max(n_dir, 1):
        probs.append(f"critique.md has {n_q} numbered answers; {NINE_QUESTIONS} per direction x {max(n_dir,1)} = {NINE_QUESTIONS*max(n_dir,1)} required")

    # standard: pass true and hash matches THIS page
    std_path = rd / "standard.json"
    if std_path.is_file():
        try:
            std = json.loads(std_path.read_text())
        except ValueError:
            std = {}
        entries = std if isinstance(std, list) else [std]
        mine = [e for e in entries if isinstance(e, dict) and e.get("page") == page.name]
        cur = sha(page)
        if not mine:
            probs.append(f"standard.json has no entry for {page.name}")
        elif not any(e.get("pass") is True and e.get("sha256") == cur for e in mine):
            probs.append(f"standard.json for {page.name}: pass is not true or hash is stale (re-run design-standard-check.py)")

    probs += craft_problems(rd, page, cfg)

    # receipts: sealed, and fresh
    rc = rd / "receipts.json"
    if not rc.is_file():
        probs.append(f"not sealed: run `design-chain-gate.py seal {rd}`")
    else:
        try:
            rec = json.loads(rc.read_text())
        except ValueError:
            rec = {}
        ent = rec.get(page.name)
        if not ent:
            probs.append(f"receipts.json has no entry for {page.name}")
        elif ent.get("sha256") != sha(page):
            probs.append(f"receipt stale for {page.name}: page edited after seal; redo the chain and seal again")
    return probs


def seal(rd: Path) -> int:
    pages = [p for p in rd.iterdir() if p.is_file() and is_page(str(p))]
    if not pages:
        print(f"seal: no page files in {rd}", file=sys.stderr)
        return 2
    rc = rd / "receipts.json"
    bad = []
    for p in pages:
        if rc.is_file():
            # ignore the existing receipt so a re-seal re-validates everything else
            probs = [x for x in chain_problems(p) if "receipt" not in x and "not sealed" not in x]
        else:
            probs = [x for x in chain_problems(p) if "not sealed" not in x]
        if probs:
            bad.append((p.name, probs))
    if bad:
        print("seal REFUSED:", file=sys.stderr)
        for name, probs in bad:
            for x in probs:
                print(f"  {name}: {x}", file=sys.stderr)
        return 2
    rec = {p.name: {"sha256": sha(p), "sealed": time.strftime("%Y-%m-%dT%H:%M:%S")} for p in pages}
    rc.write_text(json.dumps(rec, indent=2) + "\n")
    print(f"sealed {len(pages)} page(s) in {rd}")
    return 0


# ---------------------------------------------------------------- session ledger

def ledger_path(session_id: str) -> Path:
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    return STATE_DIR / f"{re.sub(r'[^A-Za-z0-9_-]', '_', session_id or 'nosession')}.json"


def load_ledger(session_id: str) -> dict:
    p = ledger_path(session_id)
    try:
        return json.loads(p.read_text())
    except (OSError, ValueError):
        return {"pages": {}, "bash_marker": 0}


def save_ledger(session_id: str, led: dict) -> None:
    ledger_path(session_id).write_text(json.dumps(led, indent=2))


def scan_roots(payload: dict) -> list[Path]:
    roots = []
    for cand in (payload.get("cwd"), os.environ.get("CLAUDE_PROJECT_DIR"), os.environ.get("DESIGN_CHAIN_EXTRA_ROOT")):
        if cand:
            roots.append(Path(cand))
    reg = Path(os.environ.get("CLAUDE_PROJECT_DIR", "")) / "instance-registry.json"
    if reg.is_file():
        try:
            for inst in json.loads(reg.read_text()).get("instances", []):
                if inst.get("path"):
                    roots.append(Path(inst["path"]))
        except ValueError:
            pass
    # de-dup by prefix
    out: list[Path] = []
    for r in sorted({r.resolve() for r in roots if r.exists()}, key=lambda p: len(str(p))):
        if not any(str(r).startswith(str(o) + os.sep) or r == o for o in out):
            out.append(r)
    return out


PRUNE = {"node_modules", ".git", "dist", "build", ".next", "coverage", "site-packages", ".venv", "venv", "__pycache__"}


def newer_pages(roots: list[Path], since: float) -> list[str]:
    found = []
    for root in roots:
        for dirpath, dirnames, filenames in os.walk(root):
            dirnames[:] = [d for d in dirnames if d not in PRUNE]
            for fn in filenames:
                if Path(fn).suffix.lower() in PAGE_EXTS:
                    fp = os.path.join(dirpath, fn)
                    try:
                        if os.path.getmtime(fp) >= since and is_page(fp):
                            found.append(fp)
                    except OSError:
                        pass
    return found


def open_pages(led: dict) -> list[tuple[str, list[str]]]:
    out = []
    for p in list(led.get("pages", {})):
        if not Path(p).exists():
            continue
        probs = chain_problems(Path(p))
        if probs:
            out.append((p, probs))
    return out


def block(msg_lines: list[str]) -> int:
    print("DESIGN CHAIN GATE (blocked): a page was made this session and its design chain is not complete.", file=sys.stderr)
    for ln in msg_lines[:40]:
        print("  " + ln, file=sys.stderr)
    print("  Steps: brief.md (verbatim owner anchors) -> directions.md (3) -> design-standard-check.py -> critique.md (9 per direction) -> proof.md -> checks/ -> gate/ -> `design-chain-gate.py seal <round>`.", file=sys.stderr)
    print("  Override is DESIGN_CHAIN_ALLOW=1 in the founder's shell only.", file=sys.stderr)
    return 2


# ---------------------------------------------------------------- hook dispatch

def hook(payload: dict) -> int:
    if os.environ.get("DESIGN_CHAIN_ALLOW") == "1":
        return 0
    ev = payload.get("hook_event_name", "")
    tool = payload.get("tool_name", "")
    ti = payload.get("tool_input") or {}
    sid = payload.get("session_id", "")
    led = load_ledger(sid)

    if ev == "PostToolUse" and tool in ("Write", "Edit", "MultiEdit"):
        fp = ti.get("file_path", "")
        if is_page(fp):
            led["pages"][str(Path(fp).resolve())] = {"first_seen": time.time(), "via": tool}
            save_ledger(sid, led)
        return 0

    if ev == "PreToolUse" and tool == "Bash":
        led["bash_marker"] = time.time() - 1
        save_ledger(sid, led)
        cmd = ti.get("command", "") or ""
        opens = open_pages(led)
        # naming an open page is only a block when the command SHOWS it; the chain's own
        # steps name the page on purpose (design-standard-check.py <page>.html)
        if opens and BASH_SHOW_RE.search(cmd):
            return block([f"{p}: {x}" for p, probs in opens for x in probs[:3]])
        return 0

    if ev == "PostToolUse" and tool == "Bash":
        since = float(led.get("bash_marker") or (time.time() - 60))
        for fp in newer_pages(scan_roots(payload), since):
            led["pages"].setdefault(str(Path(fp).resolve()), {"first_seen": time.time(), "via": "Bash"})
        save_ledger(sid, led)
        return 0

    if ev == "PreToolUse" and (tool in PUBLISH_TOOLS or tool.startswith(SHOW_TOOLS_PREFIX)):
        opens = open_pages(led)
        # publish surfaces also check what they carry, ledger or not
        if tool in PUBLISH_TOOLS:
            carried = []
            raw = ti.get("files") or ti.get("file_path") or []
            for f in (raw if isinstance(raw, list) else [raw]):
                f = f if isinstance(f, str) else (f.get("path") if isinstance(f, dict) else "")
                if not f:
                    continue
                fpath = Path(f)
                if is_page(f):
                    carried.append(fpath)
                elif fpath.suffix.lower() in (".png", ".jpg", ".jpeg", ".webp", ".pdf"):
                    for sib in fpath.parent.glob("*"):
                        if is_page(str(sib)):
                            carried.append(sib)
            for c in carried:
                probs = chain_problems(c)
                if probs:
                    opens.append((str(c), probs))
        if opens:
            return block([f"{p}: {x}" for p, probs in opens for x in probs[:3]])
        return 0

    if ev == "Stop":
        if payload.get("stop_hook_active"):
            return 0
        opens = open_pages(led)
        if opens:
            return block([f"{p}: {x}" for p, probs in opens for x in probs[:4]])
        return 0
    return 0


def main(argv: list[str]) -> int:
    if argv and argv[0] == "seal":
        return seal(Path(argv[1]).resolve())
    if argv and argv[0] == "status":
        rd = Path(argv[1]).resolve()
        pages = [p for p in rd.iterdir() if p.is_file() and is_page(str(p))]
        rc = 0
        for p in pages:
            probs = chain_problems(p)
            print(f"{p.name}: {'COMPLETE' if not probs else 'OPEN'}")
            for x in probs:
                print("   - " + x)
            rc = rc or (2 if probs else 0)
        return rc
    try:
        payload = json.load(sys.stdin)
    except Exception:
        return 0  # unreadable payload: fail open, there is nothing to judge
    return hook(payload)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
